### ISSUE TITLE
More settings like in torrentio

### ISSUE THREAD

**Issue by swiezaczek** [mhdzumair/MediaFusion#102]
I love the addon, but it would be nice if you could add results sorting options, like by size, etc. And other settings like in torrentio.

https://ibb.co/7v18Gfs

**Comment by MrMonkey42** [comment]
Request for:

- Max results per quality. For example, show only 1 stream each per quality

**Comment by mhdzumair** [comment]
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/1501608d-2fe6-4257-8a2e-d0c85c1351ae)

Implementation has been done. Thanks for your suggestions.

**Comment by MrMonkey42** [comment]
Thank you!!

**Comment by hsp1020** [comment]
Can I also add sorting option in order of resolution? (e.g. 2160p > 1080p)

**Comment by mhdzumair** [comment]
> Can I also add sorting option in order of resolution? (e.g. 2160p > 1080p > 720p)

If you enable the sort option of size this can be achievable

**Comment by hsp1020** [comment]
I want to arrange in order of seeders by resolution. But if you sort by size > seeders as you told me, it comes out like a screenshot. Therefore, I need to add the sorting option by resolution.

![Uploading Screenshot_20240218_001416_Stremio.jpg…]()

**Comment by mhdzumair** [comment]
> I want to arrange in order of seeders by resolution. But if you sort by size > seeders as you told me, it comes out like a screenshot. Therefore, I need to add the sorting option by resolution.

Got it. I'm about to release the next version. We can implement this as a separate feature. Please create a followup story for this.
