### ISSUE TITLE
contents not cataloging 

### ISSUE THREAD

**Issue by Kalabhavan** [mhdzumair/MediaFusion#103]
Just updated to latest version.contents  are not cataloging for me . Categories are checked.using with RD
![Screenshot_20240209_061242_Edge](https://github.com/mhdzumair/MediaFusion/assets/159500333/cdefd283-ccef-40a8-b015-879228c7c968)

**Comment by mhdzumair** [comment]
Click on discovery page and go back to board page again. Sometime if server load then this will re-query thr data for catalogs again.

**Comment by Kalabhavan** [comment]
Thank you for your response

I just reinstalled from community page of stremio n the issue solved
