### ISSUE TITLE
Arabp2p integration 

### ISSUE THREAD

**Issue by just-a-weird-guy** [mhdzumair/MediaFusion#104]
Can you please consider adding **arabp2p** as a source, no other addon right now provides functioning arab integration

**Comment by mhdzumair** [comment]
@just-a-weird-guy is it private torrent provider?

**Comment by just-a-weird-guy** [comment]
> @mhdzumair is it private torrent provider?

Yes i do believe so ,but with prowlarr integration shouldnt it just depend on the users own setup ?

**Comment by mhdzumair** [comment]
@just-a-weird-guy Is this site provide arabic dubbed movies? Or is it mostly native Arabic contents? 

Im asking this because, the current implementation is fully relied on the IMDB ID for only scrap if you select IMDB catalog movies or series. Secondly, [torrent name parser](https://github.com/platelminto/parse-torrent-title) which is having specific type of torrent names and design to be work mostly with English. So working with other language is torrent name not supported atm.

**Comment by just-a-weird-guy** [comment]
> @just-a-weird-guy Is this site provide arabic dubbed movies? Or is it mostly native Arabic contents?
> 
> Im asking this because, the current implementation is fully relied on the IMDB ID for only scrap if you select IMDB catalog movies or series. Secondly, [torrent name parser](https://github.com/platelminto/parse-torrent-title) which is having specific type of torrent names and design to be work mostly with English. So working with other language is torrent name not supported atm.

It provides both arabic and arabic dubbed movies or english movies with arabic captions ,but from my experience almost all of the movies listed in it (even if they have an arabic name) are also listed in imdb in english

**Comment by mhdzumair** [comment]
Okay, I can give it a try to enable it. But I have strict rule of the torrent name parse of the movie should be closely matching with IMDB movie name (fuzzy matching > 80) and the year from torrent parser should exactly match with IMDB's year data. For series only, verify the title.

**Comment by just-a-weird-guy** [comment]
> Okay, I can give it a try to enable it. But I have strict rule of the torrent name parse of the movie should be closely matching with IMDB movie name (fuzzy matching > 80) and the year from torrent parser should exactly match with IMDB's year data. For series only, verify the title.

Alright thank you very much

**Comment by mhdzumair** [comment]
Postponing until find a better solution to parse the torrent name with language other than English.

**Comment by mhdzumair** [comment]
ArabP2P can be added via Prowlarr or Jackett. MediaFusion now support both with private tracker support as well.
