### ISSUE TITLE
CRASHLOOPBACKPOFF error in MongoDb, Dramtiq and mediafusion-deployment pods while deploying locally

### ISSUE THREAD

**Issue by SainiAnmol** [mhdzumair/MediaFusion#108]
3 pods are constantly in CRASHLOOPBACKOFF state and rest 2 pods Prowlarr and Redis in running state.

Error from kubectl logs : 

exec /usr/local/bin/pipenv: exec format error

**Comment by mhdzumair** [comment]
Could you provide more information on this?
which branch did you try to setup? 

docker image tag?

**Comment by SainiAnmol** [comment]
using the develop branch and follow the same instructions from the local deployment guide

used minikube with podman

these are the pods : 

NAME                                         READY   STATUS             RESTARTS          AGE
dramatiq-worker-deployment-878844f64-pzj46   0/1     CrashLoopBackOff   196 (2m42s ago)   16h
mediafusion-deployment-7f68457d7b-hh84s      0/1     CrashLoopBackOff   68 (100s ago)     5h23m
mongodb-deployment-85bccc868d-wzxhj          0/1     CrashLoopBackOff   193 (5m5s ago)    16h
prowlarr-deployment-866f66dd8c-x8lrg         2/2     Running            0                 16h
redis-deployment-65d8857849-wkf26            1/1     Running            0                 16h


services : 

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP        17h
mediafusion-service   NodePort    10.101.x.x     <none>        80:32010/TCP   16h
mongodb-service       ClusterIP   10.97.x.x      <none>        27017/TCP      16h
prowlarr-service      ClusterIP   10.101.x.x     <none>        9696/TCP       16h
proxybroker-service   ClusterIP   10.96.x.x    <none>        8888/TCP       16h
redis-service         ClusterIP   10.103.96.124   <none>        6379/TCP       16h


I am a beginner with k8s so let me know if you need any other particular logs or details

**Comment by SainiAnmol** [comment]
I think I found the problem. Mongodb needs a armv8-2 or better and my server is older than that so thats why it's not able to run that pod.
I will close this issue.

**Comment by mhdzumair** [comment]
You could install the Lens desktop, which is a great GUI tool for k8s. 
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/943a787f-437a-4521-a095-dc4147d1abfd)

Could you show the image SHA version. also show me the deployment logs

**Comment by mhdzumair** [comment]
> I think I found the problem. Mongodb needs a armv8-2 or better and my server is older than that so thats why it's not able to run that pod. I will close this issue.

I see, in that case I would advise you create free mongo atlas cluster, https://www.mongodb.com/atlas.
Fun Fact: Im also using the free mongo atlas cluster for production 😅

**Comment by SainiAnmol** [comment]
I will try with that, thanks.

**Comment by mhdzumair** [comment]
After creating the mongo atlas cluster, you can get the mongo URI, update the `MONGO_URI` value in local-deployment.yaml file and set the mongodb replica to 0. You can ping here if you need more help on it.

**Comment by mhdzumair** [comment]
mediafusion and dramatiq worker is dependent on db and redis. So both need to be available.

**Comment by SainiAnmol** [comment]
So, I registered on atlas and copied the connection string by connecting to the cluster. Updated the mongo_uri with the connection string in local_deployment.yaml and set replicas of mongodb to 0, yet I am getting the same mongodb error :  

WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!

Is there anything I can do?
I am using a raspberryPi 4B currently.

**Comment by mhdzumair** [comment]
> WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!

Where this warning you see?

**Comment by SainiAnmol** [comment]
when I enter - kubectl logs <mongodb_podname>

I set the replica to 0 already.

**Comment by mhdzumair** [comment]
if you set the replicas to 0. then you shouldnt see any pods.  also note that once after updating the `local-deployment.yaml` file, you need to apply the changes through `kubectl apply -f deployment/local-deployment.yaml`

**Comment by SainiAnmol** [comment]
That fixed it, I forgot to apply the changes.

But now I have 2 dramtiq pods and a mediafusion pod with the same CRASHLOOPBACKOFF status.

NAME                                         READY   STATUS             RESTARTS       AGE
dramatiq-worker-deployment-878844f64-srqnm   0/1     CrashLoopBackOff   18 (96s ago)   69m
dramatiq-worker-deployment-c5f7877d5-lwdn8   0/1     CrashLoopBackOff   5 (29s ago)    3m33s
mediafusion-deployment-9f7c85f49-48bvq       0/1     CrashLoopBackOff   5 (33s ago)    3m34s
prowlarr-deployment-866f66dd8c-6cq5g         2/2     Running            0              68m
redis-deployment-65d8857849-9mtzz            1/1     Running            0              67m

The error when I do kubectl logs <pod_name> is same.
-> exec /usr/local/bin/pipenv: exec format error

any idea why they are still are resolved?

**Comment by SainiAnmol** [comment]
Could it be an architecture problem with Raspbian ARM64?

**Comment by mhdzumair** [comment]
> But now I have 2 dramtiq pods and a mediafusion pod
k8s do the rollout deployment, once the new pod healthy its stop the older one. 

> exec /usr/local/bin/pipenv: exec format error
With only this error, its hard to debug. 
could you try following?
```bash
# first create .env file with following as required. update with your own values. 
MONGO_URI=""
SECRET_KEY=""

# start the docker to debug.
docker run -v $PWD:/mediafusion --name mediafusion -d -p 8000:80 mediafusion:beta pipenv run gunicorn api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --timeout 120

```

Im thinking it might be something do with arm docker image? Because i built the image only for linux/amd64. lets se what you got on above command

**Comment by SainiAnmol** [comment]
Yeah, that would be it. I have an ARM64.

Should have checked it at the beginning. Thanks for giving your time.

Any chance that it could be deployed on ARM 64?

**Comment by mhdzumair** [comment]
> Yeah, that would be it. I have an ARM64.
> 
> Should have checked it at the beginning. Thanks for giving your time.
> 
> Any chance that it could be deployed on ARM 64?

i can build arm64 image. Have you tried the above docker commands to test?

**Comment by SainiAnmol** [comment]
Not sure where exactly to run that since I used podman to install minikube initially.

**Comment by mhdzumair** [comment]
> Not sure where exactly to run that since I used podman to install minikube initially.

```
podman run -v $PWD:/mediafusion --name mediafusion -d -p 8000:80 mediafusion:beta sh -c "pipenv run gunicorn api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --timeout 120"
```

**Comment by SainiAnmol** [comment]
getting this error 

Error: error getting default registries to try: short-name "mediafusion:beta" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"


Probably doing something wrong, I am not sure.

**Comment by mhdzumair** [comment]
```
podman run -v $PWD:/mediafusion --name mediafusion -d -p 8000:80 mhdzumair/mediafusion:beta sh -c "pipenv run gunicorn api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --timeout 120"
```

try this missed to add correct docker image. also, make sure to create the .env file before run this. 
```
# first create .env file with following as required. update with your own values. 
MONGO_URI=""
SECRET_KEY=""
```

**Comment by mhdzumair** [comment]
No need to try above. I have build the docker image for linux/arm64. 
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/1e54042d-f106-4d11-be41-bd1abd6b8d7a)

Could you try restart the deployment? it will pick up new images

**Comment by SainiAnmol** [comment]
Thanks a lot haha
I was doing what you told me and getting the same errors.

I will try with the new image.

**Comment by mhdzumair** [comment]
let me know if this solution is working or not

**Comment by SainiAnmol** [comment]
The command with podman wasn't able to execute but I executed it with
Docker and the pull request was successful. The container is running but
still the same error with everything else even after restarting.
I think I will try to do it from scratch once and see if I did something
wrong the first time.
I am a beginner at this so it's probably something I can't figure out and
that's why it's not working for me.
You've been a great help.

**Comment by SainiAnmol** [comment]
Just to confirm, what steps do I need to change for arm64 setup in the local deployment guide if I start from scratch?

**Comment by mhdzumair** [comment]
try to restart the mediafusion and dramatiq deployment with 

```
kubectl rollout restart deployment mediafusion-deployment
kubectl rollout restart deployment dramatiq-worker-deployment
```

**Comment by SainiAnmol** [comment]
I already did that, the pods are still in same state as before.

**Comment by mhdzumair** [comment]
i created another image 
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/9f07b87a-2298-4397-94df-b544b4e918cf)

could you update the image tag in `local-deployment.yaml` as `beta-arm` for mediafusion

**Comment by SainiAnmol** [comment]
Wow, that worked.

All pods are in running state now. I will try to use it and report later.

**Comment by mhdzumair** [comment]
closing as completed.
