### ISSUE TITLE
Seedr source always shows "Seedr download torrent queue is full"

### ISSUE THREAD

**Issue by SanthoshAnbalagan** [mhdzumair/MediaFusion#111]
I've configured MediaFusion with Seedr, whenever trying to play any video I'm always getting error "Seedr download torrent queue is full". But in Seedr portal there is no torrents added, even the wish list also empty. Sometimes the folder getting added with 0B. I'm trying to add media less than 2GB every time.

![image](https://github.com/mhdzumair/MediaFusion/assets/34759804/6bd9beb0-086b-4f0b-96e5-a8d11bb516c7)

**Comment by SanthoshAnbalagan** [comment]
I've 5 GB in another account, even having same issue in that account also. After clearing every folder and wish list the same error I'm getting.

**Comment by mhdzumair** [comment]
> Could you try to add a torrent/magnet from the Seedr portal?
Have you tested this?

**Comment by SanthoshAnbalagan** [comment]
Adding magnet link or uploading torrent works fine, only issue is while trying to add from Stremio

**Comment by mhdzumair** [comment]
You can connect me on tg group. i can try to help with your account

**Comment by SanthoshAnbalagan** [comment]
Please send me the link to join

**Comment by mhdzumair** [comment]
https://t.me/mediafusion_stremio_addon

**Comment by SanthoshAnbalagan** [comment]
The issue has been resolved , Thank you very much for the wonderful support @mhdzumair bro ☺🙏
