### ISSUE TITLE
File Name View Options

### ISSUE THREAD

**Issue by hsp1020** [mhdzumair/MediaFusion#113]
![Screenshot_20240213_234137_Stremio](https://github.com/mhdzumair/MediaFusion/assets/125277818/073f22d6-afa3-4ecb-ab8f-bb14fc1b63a7)

At the moment, can only see the resolution, codec, and sound information, just like screenshots. However, often have to check the full file name to actually watch a video (such as your preferred release group)

**Comment by mhdzumair** [comment]
We had the discussion to implement this feature https://github.com/mhdzumair/MediaFusion/pull/92#issuecomment-1916260563

**Comment by hsp1020** [comment]
Very good plan. When will it be implemented?

**Comment by mhdzumair** [comment]
Pretty soon.

**Comment by mhdzumair** [comment]
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/1501608d-2fe6-4257-8a2e-d0c85c1351ae)

Implementation has been done. Thanks for your suggestions.
