### ISSUE TITLE
Seedbox Integration

### ISSUE THREAD

**Issue by iwnh** [mhdzumair/MediaFusion#115]
- Add media torrent to the queue of a torrent program running on a remote seedbox
- Play media back from the remote seedbox's storage
- Ability to download multiple media files to the seedbox, eg. a whole season of episodes

**Comment by mhdzumair** [comment]
Provide the seedbox API Documentation resource as well to refer.

**Comment by mhdzumair** [comment]
I saw a list of seedbox vendors https://reddit.com/r/seedboxes/w/seedbox_vendors?utm_medium=android_app&utm_source=share

Are you using a seedbox from above list or setup your own seedbox in a server? I need more details about your requirement in order to work on the implementation.

**Comment by mhdzumair** [comment]
Added support for qBittorrent - WebDav. I hope this will be working with ElfHosted. I only tested the setup in my local.
