### ISSUE TITLE
add sorting option in order of resolution

### ISSUE THREAD

**Issue by hsp1020** [mhdzumair/MediaFusion#117]
I want to arrange in order of seeders by resolution. 
But if i sort by size > seeders as you told me, it comes out like a screenshot. 
Therefore, need to add the sorting option by resolution.

![Screenshot_20240218_001416_Stremio](https://github.com/mhdzumair/MediaFusion/assets/125277818/5de3bcbc-0973-42e3-982e-b30dce3592e1)

**Comment by mhdzumair** [comment]
closing as done
