### ISSUE TITLE
Media Fusion v3.7.1 Not Working

### ISSUE THREAD

**Issue by a95tvbox** [mhdzumair/MediaFusion#121]
![issue](https://github.com/mhdzumair/MediaFusion/assets/158166844/7b96e657-0530-450e-8973-49c9ff762bf9)

Please Fix This @mhdzumair bro
We will keep supporting you bro you're the best...🙌

**Comment by mhdzumair** [comment]
My Oracle cloud free trial ended. You can host the add-on locally. See the guideline in https://github.com/mhdzumair/MediaFusion/tree/main/deployment#mediafusion-deployment-guide-

**Comment by Rahulji7292** [comment]
Brother thanks so much for your really great and unbelievable work ❤️ , I am really very new in this field can you please please create a tutorial video to host it and add on locally I don't know coding I created GitHub only to talk to you. I will be really very greatful to you

**Comment by a95tvbox** [comment]
@mhdzumair bro it's too complicated for me...I used to install MediaFusion from https://stremio-addons.netlify.app/ but there also it shows "Addon status: Offline". Can you make the addon work like before... It was very easy to install and access too. Please bro..try to make it work again...TQ

**Comment by mhdzumair** [comment]
The service is running. See more context https://www.reddit.com/r/StremioAddons/s/gyHca68fl1
