### ISSUE TITLE
Offcloud links inside zip files dont play

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#123]
I have noticed that alot of links pulled by torrentio and mediafusion for offcloud are inside zip files for the entire season however none of these links play. They appear to play fine for both RD and AD. Im not sure if theres an issue with the links that are being scrapped as if its pulling a direct link to the zip file rather than the media file contained within. If i go directly to offcloud and click explore on the zip file the media inside is of course a different link. Is this fixable or is this an offcloud issue?

_Originally posted by @MrXT21 in https://github.com/mhdzumair/MediaFusion/discussions/122_

**Comment by mhdzumair** [comment]
I have tested these two series with zipped file (multiple episodes), 

![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/364c9302-83a3-4edf-a42b-54d48bb716ac)

Both can be played well. So it's not an issue for a torrent to be in a folder. Offcloud can provide the direct link for zipped file. 

However, I see a small issue with the implementation function of finding the correct file within zip https://github.com/mhdzumair/MediaFusion/blob/main/streaming_providers/offcloud/client.py#L78-L86, We need to use fuzzy matching as well as file index, and the last option as returning largest video file. 

@MrXT21 Each torrent files names and structures are different, so I want the exact torrent detail that you tried with MediaFusion and got into issue.

**Comment by MrXT21** [comment]
> I have tested these two series with zipped file (multiple episodes),
> 
> ![image](https://private-user-images.githubusercontent.com/44891939/307221731-364c9302-83a3-4edf-a42b-54d48bb716ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjQxNjgsIm5iZiI6MTcwODcyMzg2OCwicGF0aCI6Ii80NDg5MTkzOS8zMDcyMjE3MzEtMzY0YzkzMDItODNhMy00ZWRmLWE0MmItNTRkNDhiYjcxNmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIxMzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MmQ0MzVkZWNkMWU4YjRkYTE5NjRlNmFmYmMxODczZDhlOTBhMWM1N2Q1MDU1ZjJjZjFkNTU1MDQxMzAxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.snQJ-QnBQgJYdHnhSHYLJtJPD0SQ0sTgAevDjka6vu4)
> 
> Both can be played well. So it's not an issue for a torrent to be in a folder. Offcloud can provide the direct link for zipped file.
> 
> However, I see a small issue with the implementation function of finding the correct file within zip https://github.com/mhdzumair/MediaFusion/blob/main/streaming_providers/offcloud/client.py#L78-L86, We need to use fuzzy matching as well as file index, and the last option as returning largest video file.
> 
> @MrXT21 Each torrent files names and structures are different, so I want the exact torrent detail that you tried with MediaFusion and got into issue.

![Screenshot_](https://github.com/mhdzumair/MediaFusion/assets/44470021/27a44c11-daac-4234-a46b-b399175e68b3)

![Screenshot 2024](https://github.com/mhdzumair/MediaFusion/assets/44470021/82830306-097f-4597-959a-f6e12fc604b0)

**Comment by ragmehos** [comment]
@mhdzumair Maybe this is the same stremio bug with the name containing "[" as a problem?

**Comment by mhdzumair** [comment]
Not having free quota to test this, we need to test with following stream specifically.

**Comment by ragmehos** [comment]
I can give it a try, @MrXT21 which device are you trying this on? I wonder if this is the same issue as https://github.com/Stremio/stremio-bugs/issues/665

**Comment by mhdzumair** [comment]
> which device are you trying this on?

The screenshot is from android 😃

**Comment by mhdzumair** [comment]
> I wonder if this is the same issue as https://github.com/Stremio/stremio-bugs/issues/665

I have provided a sample magnet link on that issue. you can directly test it whether the link is containing those characters if so, we need to implement the same functionality in the seedr like renaming the files before creating the link.

**Comment by mhdzumair** [comment]
Closing as not reproducible now
