### ISSUE TITLE
Add Formula Racing contents

### ISSUE THREAD

**Issue by TheRaceDirector** [mhdzumair/MediaFusion#127]
As discussed a request to add the capability of Formula racing classes to MediaFusion, this is very challenging do to the fact that like most sport, it does not follow a TV show structure.
Due to uploaders uploading different content, from different sources, in different qualities, with different naming & folder structures, this will be complex.
Also formula racing sessions are not as predictable with sessions sometimes being delayed/moved. Mixed with the occasional sprint weekend and opening ceremony.

The Formula function added to MediaFusion should support multiple resolutions and multiple sources. 
While being resilient to not miss sessions (unlike if simple regex was used to assign files to episodes).

This will add a separate category to MediaFusion for formula racing, and this will be a tidy way to navigate each round, then play content as the desired quality.

MediaFusion will have to implement robust scraping to ensure all content is made available to addon users, as well as running frequently, so sessions are watchable soon after they are uploaded.

**Comment by TheRaceDirector** [comment]
Issue description updated

**Comment by mhdzumair** [comment]
Closing as done. Let's open a new issue for followup on adding another uploader.
