### ISSUE TITLE
No default database defined or provided while trying to deploy locally using docker

### ISSUE THREAD

**Issue by SainiAnmol** [mhdzumair/MediaFusion#131]
I am trying to deploy using docker on rpi 4B. Since mongoDB is not supported, I am trying to deploy using mongo atlas. I replaced the MONGO_URI parameter with connection string that I got after creating an account and database on atlas. Also, removed all the "Depends_on" parameters. Still the error of "no database defined or provided" is persisting.

**Comment by mhdzumair** [comment]
> "no database defined or provided" 
Where did you see the error?

**Comment by SainiAnmol** [comment]
Docker logs of the container with healthcheck

**Comment by mhdzumair** [comment]
Have you also removed mongodb container definition? 

Could you past some logs here?

**Comment by SainiAnmol** [comment]
[log.log](https://github.com/mhdzumair/MediaFusion/files/14467832/log.log)

**Comment by mhdzumair** [comment]
> No default database name defined or provided.

Ohh boy, you missed to mention  “database name”. Add `/MediaFusion` at the end of the MONGO_URI.  

Thanks for bringing this. I'll update the documentation.

**Comment by SainiAnmol** [comment]
I added that and still the same error. Can it be anything else?

**Comment by mhdzumair** [comment]
Connect me through the tg. I suspect your MONGO_URI has the issue.

**Comment by SainiAnmol** [comment]
Sure.
