### ISSUE TITLE
Cannot Install with any premium addon 

### ISSUE THREAD

**Issue by iamanonym0us** [mhdzumair/MediaFusion#134]
Cannot configure the add-on with any premium service. It throws an error saying It cannot encrypt user data. Please fix.

**Comment by mhdzumair** [comment]
Fixed the issue and release 3.7.3

**Comment by Sephirod** [comment]
It's doing it again

**Comment by mhdzumair** [comment]
> It's doing it again

What issue you're facing? I just installed now with RD, it's working fine.

**Comment by Sephirod** [comment]
Same as OP, red splash saying there was an error encrypting user data

**Comment by mhdzumair** [comment]
which URL used for mediafusion?

**Comment by mhdzumair** [comment]
please provide more information about the service name you're trying to use, which MediaFusion URL elfhosted version or https://mediafusion.fun

**Comment by Sephirod** [comment]
> please provide more information about the service name you're trying to use, which MediaFusion URL elfhosted version or https://mediafusion.fun

the .fun URL

And I'm trying to use it with RD. Although I only checked both TV options (Live TV and MediaFusion Search TV) in the Catalog Configuration since I already have quite a few add-ons for the rest.

**Comment by mhdzumair** [comment]
If you only need the live TV options, then you don't need the RD. However, I would like to see the error you're facing. If possible, open the developer console and go to network tab and click on the installation, then send me a ss.

**Comment by Sephirod** [comment]
It's no longer showing the red splash error for some reason but it still doesn't do anything it seems : 

![image](https://github.com/mhdzumair/MediaFusion/assets/14348989/bb2e2fdf-a482-4f5c-a65b-7f2867fe950d)

**Comment by mhdzumair** [comment]
Ohh okay that make sense. There was Copy installation button implementation, 
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/6976ae05-12dc-42b2-93ba-081c8dd77152)

I see its raise an exception on prod URL. I'll fix that issue. Thanks for pointing out.

**Comment by mhdzumair** [comment]
Fixed
