### ISSUE TITLE
ERR_OPENING_MEDIA failed to fetch when installing addon (Locally hosted)

### ISSUE THREAD

**Issue by kranth1reddy** [mhdzumair/MediaFusion#140]
I'm trying to host my own MediaFusion addon followed all the steps described in this [guide](https://github.com/mhdzumair/MediaFusion/blob/main/deployment/docker-compose/README.md) but stremio is throwing an error whenever i try to install the locally built addon.

Image for reference:
<img width="459" alt="Screenshot 2024-03-12 at 6 08 08 PM" src="https://github.com/mhdzumair/MediaFusion/assets/163208120/287f1c21-a15b-431b-9ab2-aa89ded00d8e">

I have already enabled local files addon and restarted stremio before installing MediaFusion addon:
<img width="459" alt="Screenshot 2024-03-12 at 6 11 12 PM" src="https://github.com/mhdzumair/MediaFusion/assets/163208120/fe2c2721-32ad-4797-90df-577b801b8e53">

Stremio operating system: MacOS 14.3

Hosting on a raspberrypi, i can access MediaFusion UI using this URL:
https://raspberrypi.local/configure

**Comment by mhdzumair** [comment]
Which deployment method you tried? Have you created the ssl cert correctly for the domain name you mentioned and then setup the domain name in the env?

**Comment by kranth1reddy** [comment]
I have followed this guide:
https://github.com/mhdzumair/MediaFusion/blob/main/deployment/docker-compose/README.md

And yes i have my domain (raspberrypi.local) updated in env file and i'm able to access mediaFusion using the URL: 
https://raspberrypi.local

Image:
<img width="1021" alt="Screenshot 2024-03-12 at 8 10 58 PM" src="https://github.com/mhdzumair/MediaFusion/assets/163208120/e9606097-5699-4412-94e2-4d47243bbcd9">

But when i click install addon stremio is throwing the error

**Comment by mhdzumair** [comment]
Have you also updated the domain name in the nginx.conf ? 

Also please provide the mediafusion container logs it would be good to debug the issue.

**Comment by mhdzumair** [comment]
Any updates?

**Comment by kranth1reddy** [comment]
okay, i'm not implementing SSL any more since i plan to use Cloudflare tunnels to access mediafusion.

I was able to install mediafusion addon on stremio but i'm facing couple of issues here, can you please help me with this.

1: i don't see album art for movies.
<img width="1021" alt="Screenshot 2024-03-15 at 2 22 22 PM" src="https://github.com/mhdzumair/MediaFusion/assets/163208120/00c1d3b9-79a4-462d-bd49-7092dca9c324">

2: After clicking a movie link and tried to watch, i'm getting a play back error.

Here is the log from mediafusion container.

`INFO::15-Mar-24 18:17:36 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt1160419.json HTTP/1.1" 404
INFO::15-Mar-24 18:17:43 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt14230458.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:46 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/series/tt2356777.json HTTP/1.1" 404
INFO::15-Mar-24 18:17:48 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt7527682.json HTTP/1.1" 404
INFO::15-Mar-24 18:17:49 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt13510660.json HTTP/1.1" 404
INFO::15-Mar-24 18:17:49 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt0897413.json HTTP/1.1" 404
INFO::15-Mar-24 18:17:50 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/catalog/movie/telugu_tcrip.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:50 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt28288786.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:55 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt27657791.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:55 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt26997803.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:56 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt13885428.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:56 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt22170036.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:57 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt15457802.json HTTP/1.1" 200
INFO::15-Mar-24 18:17:57 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt29996716.json HTTP/1.1" 200
INFO::15-Mar-24 18:18:06 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt27721719.json HTTP/1.1" 200
INFO::15-Mar-24 18:18:07 - 195.252.206.63 - "GET http://mediafusion.example.com/***MASKED***/meta/movie/tt31032531.json HTTP/1.1" 200`

**Comment by mhdzumair** [comment]
I have deleted your message due to your IP was in the log. So the issue is with your problem for no poster image is, You need to correctly configure the `host_url` which pointing out to the DNS name of the Cloudflare tunnel.  And for the 404 metadata endpoint is because that specific metadata doesn't scrape and stored in db. You can ignore the metadata endpoint.

**Comment by mhdzumair** [comment]
See the configuration doc in https://github.com/mhdzumair/MediaFusion/blob/main/docs/configuration.md#mediafusion-environment-configuration-guide

**Comment by kranth1reddy** [comment]
Thank you! i did not realize that i have my IP exposed.

okay finally i was able to watch from mediafusion addon with all poster images too.

<img width="1021" alt="Screenshot 2024-03-15 at 3 04 53 PM" src="https://github.com/mhdzumair/MediaFusion/assets/163208120/652fade2-b62d-4f37-94be-5640767345ba">


Thanks for the help.

i only see like 31-100 movies in TeluguTCRip Movies or TeluguHD Movies of stremio Discover section, is there anything i should be doing with scraping from prowlarrrr or settings to get more movies from the options i selected ?

**Comment by mhdzumair** [comment]
The tamilmv and tamilblasters scraper script only scrape first page. We will improve the scraper script further. For now you can enable tamilmv live search option then you can search a movie/series name in the stremio search bar. It will try to scrap the data from tamilmv.

**Comment by kranth1reddy** [comment]
Great. i have updated this variable to true
ENABLE_TAMILMV_SEARCH_SCRAPER="true"

I think that is all i can do for now, Thanks for your support, I appreciate it.

**Comment by mhdzumair** [comment]
Added option to run scrapers manually by go into /scraper url.

**Comment by Neo402** [comment]
> Thank you! i did not realize that i have my IP exposed.
> 
> okay finally i was able to watch from mediafusion addon with all poster images too.
> <img alt="Screenshot 2024-03-15 at 3 04 53 PM" width="1021" src="https://private-user-images.githubusercontent.com/163208120/313307073-652fade2-b62d-4f37-94be-5640767345ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTQyNDMsIm5iZiI6MTcxMTkxMzk0MywicGF0aCI6Ii8xNjMyMDgxMjAvMzEzMzA3MDczLTY1MmZhZGUyLWI2MmQtNGYzNy05NGJlLTU2NDA3NjczNDViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxOTM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjkxMGUwZmJmMTBhOWU2N2M1Y2IwNDQwNjY0N2MwN2Q3ZDA0YjJmYjQ1MDUxMzNjYzllNmViZTFiOThhYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.seb7IlQS09reUJvRchToXgcJvCuvLx7cayKIHaHAM_8">
> 
> Thanks for the help.
> 
> i only see like 31-100 movies in TeluguTCRip Movies or TeluguHD Movies of stremio Discover section, is there anything i should be doing with scraping from prowlarrrr or settings to get more movies from the options i selected ?

I'm getting same "Failed to Fetch" error. how did you resolved it.. could you elaborate?

**Comment by kranth1reddy** [comment]
@Neo402 Stremio only loads addons if they are on https it seems, probably you need to configure the ssl correctly and site should be accessible from browser. something like https://mediafusion.yoursite.com not http://mediafusion.yoursite.com

**Comment by KarthiSurfer** [comment]
@kranth1reddy I'm getting the same error too, SSL also configured correctly able to access mediafusion with site no secure warning, mediafusion is showing unhealthy can you please help where I'm doing wrong

**Comment by mhdzumair** [comment]
@KarthiSurfer provide me the mediafusion container logs. Make sure to mask any ip addresses.

**Comment by Neo402** [comment]
@mhdzumair As above mentioned by @KarthiSurfer same here for me. Attached mediafusion container logs. Please check
[_docker-compose_mediafusion_1_logs.txt](https://github.com/mhdzumair/MediaFusion/files/14825726/_docker-compose_mediafusion_1_logs.txt)
