### ISSUE TITLE
Content did not load , error occurred 

### ISSUE THREAD

**Issue by chaitanyamadugula** [mhdzumair/MediaFusion#141]
It is not showing anything [![Screenshot_20240314-144836.png](https://github.com/mhdzumair/MediaFusion/assets/118282568/8c480e8e-fc31-4817-ace8-397bed4d4403)

**Comment by chaitanyamadugula** [comment]
Iam using your official media fusion addon present in the stremio community
add-ons
Could you please see it .🙂

**Comment by mhdzumair** [comment]
There are two addon. https://mediafusion.fun and https://mediafusion.elfhosted.com 

You have to configure the addon from either of above links and setup the preferences. You need to enable the catalogs, resolutions and etc. By default no data will be show to you.

**Comment by chaitanyamadugula** [comment]
I used used both the add-ons on my mobile but it is showing the same error.
There is no addon information present.could you please resolve it.

**Comment by mhdzumair** [comment]
I would like to see your configuration you configured. Send a screen shot of the configuration page expect the authentication details.

**Comment by chaitanyamadugula** [comment]
I uninstalled the stremio app and addon and freshly installed it and its
working now
Thanks bro for your value time☺️
