### ISSUE TITLE
Live tv channels are not loading

### ISSUE THREAD

**Issue by amaraaryan** [mhdzumair/MediaFusion#146]
I have installed the addon from this source https://mediafusion.elfhosted.com/. And now the live tv is not working please solve it😭![IMG-20240320-WA0001.jpg](https://github.com/mhdzumair/MediaFusion/assets/114204079/fec42084-62d1-4f34-95b2-c865215ca6bf)

**Comment by mhdzumair** [comment]
Its working for me with elfhosted. 
![SmartSelect_20240320_203059_Stremio](https://github.com/mhdzumair/MediaFusion/assets/44891939/eba5ce0e-b779-478c-b68d-1f1f7cddb016)

You might hit the rate limit of the elfhosted. They have a different rate limiting on free community addon. You can find more information about their rate limiting detail through https://mediafusion.elfhosted.com
