### ISSUE TITLE
Live tv not working 

### ISSUE THREAD

**Issue by amaraaryan** [mhdzumair/MediaFusion#148]
I have installed the addon from this source https://mediafusion.elfhosted.com/. And now the live tv is not working please solve it😭![IMG-20240320-WA0001.jpg](https://github.com/mhdzumair/MediaFusion/assets/114204079/4d79fdf5-e246-4f20-91c1-0f2b20a10499)

**Comment by mhdzumair** [comment]
Duplicated #147
