### ISSUE TITLE
Live tv not working 

### ISSUE THREAD

**Issue by chaitanyamadugula** [mhdzumair/MediaFusion#149]
Live TV has been working for the past 3 days but today it is not.![Screenshot_20240320-200740.png](https://github.com/mhdzumair/MediaFusion/assets/118282568/d32bbcb4-99c3-4bc7-9843-ac06d9e8527c)

 I have installed the addon from this source https://mediafusion.elfhosted.com/.

**Comment by mhdzumair** [comment]
Duplicated #147
