### ISSUE TITLE
Media fusion down 

### ISSUE THREAD

**Issue by grm18** [mhdzumair/MediaFusion#150]
Media fusion no longer shows up in streams and settings lands in cloudfare error page. 
Used to work earlier in stremio

**Comment by mhdzumair** [comment]
Hi @grm18, sorry for late reply. As I announced in several releases note that published in the Reddit post, the https://mediafusion.fun community version won't work. 

You can either self-host the MediaFusion add-on or you can use ElfHosted community version at 
https://mediafusion.elfhosted.com 
Note that I'm not affiliated with their services.
