### ISSUE TITLE
Not getting Tamilbalsters and TamilMV torrents

### ISSUE THREAD

**Issue by Nonamenonsense** [mhdzumair/MediaFusion#151]
Hello there i've recently noticed i am not getting torrent of Tamilbalsters and TamilMV in Stremio. Checked the two sites they are working fine it seems.  I'm using elfhsoted Mediafusion v3.7.5 version.

Tamilbalsters - https://www.1tamilblasters.eu/
TamilMV - https://www.1tamilmv.tax/

**Comment by mhdzumair** [comment]
Is it resolved? The elfhosted have a different rate limits you may affected by that.

**Comment by Nonamenonsense** [comment]
Yeah I didn't get torrent for some movies but it is working fine for latest movies. I think those sites maybe didn't have that movie. Mediafusion works fine no problem.

Also it returns empty content when I sort by language in Live tv. For ex. I selected Tamil but it shows This addon returned empty content.

**Comment by mhdzumair** [comment]
Yeah its a known bug of genre sorting on this release. Ill fix it on next version

**Comment by Nonamenonsense** [comment]
Cool thanks man
