### ISSUE TITLE
Media Fusion not running in docker compose with mongodb atlas

### ISSUE THREAD

**Issue by KarthiSurfer** [mhdzumair/MediaFusion#156]
Mongodb atlas showing this below error 

No default database name defined or provided detailed log below

sample mongodb URI - mongodb+srv://username:<my password>@cluster0.s1ltpre.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/mediafusion

**Comment by KarthiSurfer** [comment]
now I'm trying with mongodb atlas and getting this error log please check
Logo
Containers>docker-compose_mediafusion_1>Logs
Container logs


admin
Logs
Search...

Filter search results
Auto refresh
Fetch

All logs
Lines
1000

Show timestamp

Show line numbers

Wrap line
[2024-03-30 10:54:56 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-03-30 10:54:56 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-03-30 10:54:56 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-03-30 10:54:56 +0000] [7] [INFO] Booting worker with pid: 7
[2024-03-30 10:54:57 +0000] [8] [INFO] Booting worker with pid: 8
[2024-03-30 10:54:57 +0000] [9] [INFO] Booting worker with pid: 9
[2024-03-30 10:54:57 +0000] [10] [INFO] Booting worker with pid: 10
/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/src/cinemagoer/imdb/utils.py:990: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if beginTag is "":
/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/src/cinemagoer/imdb/utils.py:990: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if beginTag is "":
/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/src/cinemagoer/imdb/utils.py:990: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if beginTag is "":
/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/src/cinemagoer/imdb/utils.py:990: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if beginTag is "":
[2024-03-30 10:55:11 +0000] [10] [INFO] Started server process [10]
[2024-03-30 10:55:11 +0000] [10] [INFO] Waiting for application startup.
WARNING::30-Mar-24 10:55:11 - Error initializing database: No default database name defined or provided., retrying in 1 seconds...
[2024-03-30 10:55:11 +0000] [9] [INFO] Started server process [9]
[2024-03-30 10:55:11 +0000] [9] [INFO] Waiting for application startup.
WARNING::30-Mar-24 10:55:11 - Error initializing database: No default database name defined or provided., retrying in 1 seconds...
[2024-03-30 10:55:12 +0000] [8] [INFO] Started server process [8]
[2024-03-30 10:55:12 +0000] [8] [INFO] Waiting for application startup.
[2024-03-30 10:55:12 +0000] [7] [INFO] Started server process [7]
[2024-03-30 10:55:12 +0000] [7] [INFO] Waiting for application startup.
WARNING::30-Mar-24 10:55:12 - Error initializing database: No default database name defined or provided., retrying in 1 seconds...
WARNING::30-Mar-24 10:55:12 - Error initializing database: No default database name defined or provided., retrying in 1 seconds...
WARNING::30-Mar-24 10:55:12 - Error initializing database: No default database name defined or provided., retrying in 2 seconds...
WARNING::30-Mar-24 10:55:12 - Error initializing database: No default database name defined or provided., retrying in 2 seconds...
WARNING::30-Mar-24 10:55:13 - Error initializing database: No default database name defined or provided., retrying in 2 seconds...
WARNING::30-Mar-24 10:55:13 - Error initializing database: No default database name defined or provided., retrying in 2 seconds...
WARNING::30-Mar-24 10:55:14 - Error initializing database: No default database name defined or provided., retrying in 4 seconds...
WARNING::30-Mar-24 10:55:14 - Error initializing database: No default database name defined or provided., retrying in 4 seconds...
WARNING::30-Mar-24 10:55:15 - Error initializing database: No default database name defined or provided., retrying in 4 seconds...
WARNING::30-Mar-24 10:55:15 - Error initializing database: No default database name defined or provided., retrying in 4 seconds...
WARNING::30-Mar-24 10:55:18 - Error initializing database: No default database name defined or provided., retrying in 8 seconds...
WARNING::30-Mar-24 10:55:18 - Error initializing database: No default database name defined or provided., retrying in 8 seconds...
WARNING::30-Mar-24 10:55:19 - Error initializing database: No default database name defined or provided., retrying in 8 seconds...
WARNING::30-Mar-24 10:55:19 - Error initializing database: No default database name defined or provided., retrying in 8 seconds...
ERROR::30-Mar-24 10:55:26 - Failed to initialize database after several attempts.
[2024-03-30 10:55:26 +0000] [10] [ERROR] Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/starlette/routing.py", line 711, in startup
    await handler()
  File "/mediafusion/api/main.py", line 61, in init_server
    await database.init()
  File "/mediafusion/db/database.py", line 50, in init
    raise e
  File "/mediafusion/db/database.py", line 28, in init

**Comment by mhdzumair** [comment]
@KarthiSurfer Make sure to add the Database name in the connection string. Example Database name is `mediafusion`.
```yaml
          - name: MONGO_URI
            value: "mongodb+srv://<username>:<password>@<cluster-url>/<database-name>?retryWrites=true&w=majority"
```

**Comment by KarthiSurfer** [comment]
hi @mhdzumair, after adding the above getting this warning and still application not loading

WARNING::31-Mar-24 02:46:08 - Error initializing database: SSL handshake failed: ac-gazzobi-shard-00-01.s1ltpre.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-gazzobi-shard-00-02.s1ltpre.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-gazzobi-shard-00-00.s1ltpre.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6608ce5211f7715d7b4a9d63, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-gazzobi-shard-00-00.s1ltpre.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect("SSL handshake failed: ac-gazzobi-shard-00-00.s1ltpre.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)")>, <ServerDescription ('ac-gazzobi-shard-00-01.s1ltpre.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect("SSL handshake failed: ac-gazzobi-shard-00-01.s1ltpre.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)")>, <ServerDescription ('ac-gazzobi-shard-00-02.s1ltpre.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect("SSL handshake failed: ac-gazzobi-shard-00-02.s1ltpre.mongodb.net:27017: [('SSL routines', '', 'tlsv1 alert internal error')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)")>]>, retrying in 4 seconds...

**Comment by KarthiSurfer** [comment]
my env file

HOST_URL="https://mediafusion.local"
MONGO_URI="mongodb+srv://username:<password>@cluster0.s1ltpre.mongodb.net/mediafusion?retryWrites=true&w=majority&appName=Cluster0/"
REDIS_URL="redis://redis:6379"
PROWLARR_URL="http://192.168.1.18:9696"
PROWLARR_API_KEY=7f9ba502544447f18735bb43339f30ee
PROWLARR_IMMEDIATE_MAX_PROCESS=5
PROWLARR_IMMEDIATE_MAX_PROCESS_TIME=15
PROWLARR_SEARCH_INTERVAL_HOUR="24"
IS_SCRAP_FROM_TORRENTIO="true"
ENABLE_RATE_LIMIT="false"
ENABLE_TAMILMV_SEARCH_SCRAPER="true"
SECRET_KEY=8604038410a65bdacf444c2bb0a0b574
PREMIUMIZE_OAUTH_CLIENT_ID=your_client_id
PREMIUMIZE_OAUTH_CLIENT_SECRET=your_client_secret

**Comment by KarthiSurfer** [comment]
thank you @mhdzumair , mediafusion is running now, but not able to configure the addon in stremio, addon is showing unhealthy and not reachable via mediafusion.local,only via ip address please help 
![Screenshot_2024-03-31-09-18-58-801_com stremio one](https://github.com/mhdzumair/MediaFusion/assets/22189368/206a362f-05fd-49a7-987d-33a858be0720)
![Screenshot_2024-03-31-09-19-28-349_com android chrome](https://github.com/mhdzumair/MediaFusion/assets/22189368/7d951131-13db-481e-b74a-0a3a0c76d537)
![Screenshot_2024-03-31-09-19-20-701_com android chrome](https://github.com/mhdzumair/MediaFusion/assets/22189368/ac44d6e5-440a-40b4-8f2e-f7acf94092d9)

**Comment by mhdzumair** [comment]
Please configure the ssl and the dns host according to the docs. Stremio only support https for media url. Also regarding the mediafusion unhealthy, provide me the log of the container.

**Comment by KarthiSurfer** [comment]
hi @mhdzumair ssl has been configured and able to reach https://mediafusion.local in my local machine with a security warning, is this correct behaviour and for the media fusion container log is below attached
[docker-compose_mediafusion_1_logs.txt](https://github.com/mhdzumair/MediaFusion/files/14819695/docker-compose_mediafusion_1_logs.txt)
please help

**Comment by mhdzumair** [comment]
it shouldn't show the security warning. make sure to run `mkcert -install` in local to trust the ssl certificate. also the from the logs you provided for mediafusion container doesnt have any issues. may be the healthcheck shows unhealthy while starting up the server. check this if this is the case.

**Comment by KarthiSurfer** [comment]
yes @mhdzumair , you are correct, able to configure the addon now, installed the rootCA from mkcert in all laptops , it's accessible on all the laptop locally, the sports section is working fine but no posters for movies and series, is it possible to make it work on android mobile and android tv because the url won't resolve because of host file modification can't be done on mobile and android tv

**Comment by KarthiSurfer** [comment]
@mhdzumair, even before starting the server it turns unhealthy and after installing the rootCA from mkcert able to access mediafusion.local without any certificate issues in laptop, the movies and series section shows all empty only the sports section is populated, when deploying locally it seems like it's not accessible via mobile and android tv, since mediafusion.local won't resolve to IP address, attaching the log please help

[docker-compose_mediafusion_1_logs (1).txt](https://github.com/mhdzumair/MediaFusion/files/14821133/docker-compose_mediafusion_1_logs.1.txt)

**Comment by mhdzumair** [comment]
At starting, it won't populate the data out of the box. go to https://mediafusion.local/scraper page and trigger the scrapers. 

The guideline only intended for local deployment. to access it from outside you can use [cloudflare tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-remote-tunnel/) (you need a domain) or simply with [localtunnel](https://theboroer.github.io/localtunnel-www/)

**Comment by KarthiSurfer** [comment]
thanks you so much @mhdzumair, I'm closing this as resolved thank you for this addon
