### ISSUE TITLE
Adding of secondary F1 source

### ISSUE THREAD

**Issue by TheRaceDirector** [mhdzumair/MediaFusion#157]
Following on from the completed issue #127 
Request to add  secondary source to the Formula Racing section of the addon.
.../profile/F1Carreras/torrents/0

### Scraping Details
Combine into 1 TV show, where each episode contains a match between "Formula1" and "20xx" and "Roundxx"
Example TV show name would be "2024 Round03"

Episode name can be pulled from the two values before ".1080p" (this allows for redundancy where the order has been inconsistent)
Example episode name would be "Race F1TV"

Example upload name:
`Formula1.2024x18.Round03.Australia.Race.F1TV.1080p.WEB-DL.AAC2.0.H.264-F1Carreras
`
### Torrent details
Unfortunately a suitable cover image is not provided, a sample screengrab is, but this contains spoilers and should not be used.
The MediaFusion default F1 poster should be used.

Each description contains the following information:
```
  Video:
  Container: MKV
  Quality: 1080p
  Bitrate: 6000 kb/s
  Frame Rate: 50 fps

  Audios:
  English(SkySports), German, French, Spanish, Dutch, Portuguese, Natural Sound
  Format: AAC
  Bit Rate: 196 kb/s
  Channels: 2 channels
  Sampling Rate: 48.0 kHz
```

This is a multi-language upload which will allow for people to watch with local commentary.

**Comment by mhdzumair** [comment]
Why not use spoiler image? I like their poster, :) we can also use default poster.

**Comment by TheRaceDirector** [comment]
The poster is good, but for example on the last upload (Aus GP race) you can see that it shows which cars are starting in which order. That would be a huge spoiler for "previous episodes".
We may have to use the default formula racing poster.
