### ISSUE TITLE
Elfhosted MediaFusion does not generate results

### ISSUE THREAD

**Issue by ashravi92** [mhdzumair/MediaFusion#158]
I subscribed to elfhosted mediafusion but it is not scraping or returning any results.

**Comment by mhdzumair** [comment]
Have you configure the mediafusion catalogs, resolutions etc correctly? please provide more information

**Comment by ashravi92** [comment]
I think I did not select any resolution. Picking resolution fixed the issue. Is there anyway we can have few resolutions as default so that it is more intuitive for novice users.
