### ISSUE TITLE
This addon returned empty content

### ISSUE THREAD

**Issue by Neo402** [mhdzumair/MediaFusion#161]
First of all Thanks for this amazing addon..🙏
Self hosted on Raspberry pi. I Followed installation guide and successfully installed addon on Stremio. But no catalogs on homepage no search results nothing found. What wrong i have done ![Screenshot 2024-04-03 021541](https://github.com/mhdzumair/MediaFusion/assets/126967091/f4a8a7e1-f2d5-4547-ace0-c689bd9db849)

**Comment by mhdzumair** [comment]
Initially it won't scrape the data at start. All the scraping functions are schedule jobs. Apart from this you can have ability to trigger it manually by going into https://mediafusion.local/scraper

**Comment by KarthiSurfer** [comment]
@mhdzumair how can i change the URL for tamilrockers and tamilblasters, I have ran the scraper and waited for a day but the posters were not showing, from the logs i can see that the URL is not connecting, please help

**Comment by mhdzumair** [comment]
Could you share the logs? The urls are working for me. If your stremio shows the movie and not showing the poster then you have missed to setup host_url in the config.

**Comment by vgupta1192** [comment]
@mhdzumair mediafusion scrappers are not working anymore. Just checked. Kindly fix it ASAP

**Comment by mhdzumair** [comment]
What part of the scrapers are not working? Coud you provide me the logs?

**Comment by vgupta1192** [comment]
All hindi category as well as english category![image](https://github.com/mhdzumair/MediaFusion/assets/45812901/0418d920-a2fb-44e7-8030-6495832d34d2)

**Comment by mhdzumair** [comment]
> All hindi category as well as english category!

So you're talking about community version. just fyi, i asked elfhosted to shutdown the background worker due to issue with schedulers. Currently its triggerring multiple duplicates of scheduling across community version deployment and other tenants deployment. This making lot more traffic on scraping site and elfhosted ips were get banned. 

This issue was addressed and fixed in dev branch. So this will be resolved in next release.

**Comment by vgupta1192** [comment]
So can you kindly suggest from which link to install the mediafusion add on.
I have installed elfhosted community version.

**Comment by KarthiSurfer** [comment]
hi @mhdzumair, please find the logs 
[docker-compose_dramatiq-worker_1_logs (1).txt](https://github.com/mhdzumair/MediaFusion/files/14883986/docker-compose_dramatiq-worker_1_logs.1.txt)

**Comment by Neo402** [comment]
Hi @mhdzumair. please check..
[_docker-compose_dramatiq-worker_1_logs.txt](https://github.com/mhdzumair/MediaFusion/files/14885310/_docker-compose_dramatiq-worker_1_logs.txt)

**Comment by KarthiSurfer** [comment]
> Hi @mhdzumair. please check.. [_docker-compose_dramatiq-worker_1_logs.txt](https://github.com/mhdzumair/MediaFusion/files/14885310/_docker-compose_dramatiq-worker_1_logs.txt)

only the catalog for tamilmv and tamilblasters are showing empty content, seems like it's not scraping the sites, please help

**Comment by vgupta1192** [comment]
> > All hindi category as well as english category!
> 
> 
> 
> So you're talking about community version. just fyi, i asked elfhosted to shutdown the background worker due to issue with schedulers. Currently its triggerring multiple duplicates of scheduling across community version deployment and other tenants deployment. This making lot more traffic on scraping site and elfhosted ips were get banned. 
> 
> 
> 
> This issue was addressed and fixed in dev branch. So this will be resolved in next release. 

Hi @mhdzumair when is the next release planned. Any ETA?

**Comment by mhdzumair** [comment]
Closing as done
