### ISSUE TITLE
Local Hosted Docker Compose - Issue with catalog and prowlarr

### ISSUE THREAD

**Issue by KarthiSurfer** [mhdzumair/MediaFusion#164]
Hi @mhdzumair , I'm commenting on other users issue for support , to clear up the confusion creating a new issue for myself

I'm running the mediafusion locally with docker compose and mongodb atlas, with SSL >> my issue is catalogs are not at all showing and prowlarr streams are not fetching attaching the screenshot and logs

![Screenshot_2024-04-06-20-08-01-066_com android chrome](https://github.com/mhdzumair/MediaFusion/assets/22189368/cf8ba0d0-7dcc-493a-a9f4-194f65c11421)

This is my .env - let me know if changes were needed

![Screenshot_2024-04-06-20-09-37-905_com foxdebug acodefree-edit](https://github.com/mhdzumair/MediaFusion/assets/22189368/ff0dcddb-14bb-40ea-8929-0a539ab4f68f)

all the catalogs are returning empty and the sports section is populated with images and streams correctly after manually  running the scrapers

![Screenshot_2024-04-06-20-11-46-161_com stremio one](https://github.com/mhdzumair/MediaFusion/assets/22189368/5ae736f5-bec9-4935-86f9-67c7ccd723db)
![Screenshot_2024-04-06-20-11-48-853_com stremio one](https://github.com/mhdzumair/MediaFusion/assets/22189368/48fe6f69-e601-4e11-894c-b574aab10bb7)
![Screenshot_2024-04-06-20-11-54-397_com stremio one](https://github.com/mhdzumair/MediaFusion/assets/22189368/c98df3e0-97db-4da9-863d-63e25bf70ac0)

and while checking the logs for prowlarr I'm getting this error

WARNING::06-Apr-24 14:14:43 - Failed to fetch API data from Prowlarr for 3 Body Problem 

the API is correct and same as in the .env and I have checked 

and while running the scrappers for tamilmv and tamilblasters getting this error in the attached log from dramatiq

[docker-compose_dramatiq-worker_1_logs.txt](https://github.com/mhdzumair/MediaFusion/files/14893919/docker-compose_dramatiq-worker_1_logs.txt)

please assist when you have time

Appreciate your time and effort

**Comment by KarthiSurfer** [comment]
@mhdzumair, prowlarr is working correctly but the prowlar results were not showing inside stremio attaching the log
[docker-compose_dramatiq-worker_1_logs (3).txt](https://github.com/mhdzumair/MediaFusion/files/14930395/docker-compose_dramatiq-worker_1_logs.3.txt)

**Comment by mhdzumair** [comment]
In the new version, You can enable `prowlarr_live_title_search=True` for running title search in live, so make sure to set this env value if you want to have direct search. Otherwise, it will run the title search in background then, after cache get expired, you will see the results.
