### ISSUE TITLE
Add scrapy for Arab content

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#166]
scraping site: https://www.arab-torrents.com/index.php

**Comment by JubailDX** [comment]
any update 👀

**Comment by mhdzumair** [comment]
Planning to add this soon. Worked on other priorities.

**Comment by mhdzumair** [comment]
It seems the site is no longer being maintained, and even the torrents are not alive with seeders. So, it's a waste of time setting up Scrapy for it. Do you know any better sites for scraping Arabic content? It should be a **public torrent**.

**Comment by SPOILER-hycom** [comment]
did any of you reach a good point?
