### ISSUE TITLE
Media Fusion Latest Version unhealthy 

### ISSUE THREAD

**Issue by KarthiSurfer** [mhdzumair/MediaFusion#169]
@mhdzumair, health check returns this

OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown

while opening the localhost:8000/health - it's showing healthy

1tamilmv and tamilblaster scrapers are not getting any results

**Comment by karthikilan** [comment]
Hi Buddy, How do I run a health check ?

**Comment by karthikilan** [comment]
> @karthikilan, if u have deployed the addon locally either using docker compose or kubernetes, then you can directly visit the localhost:8000 and see the results 

Oh @KarthiSurfer ... I am using the elfhosted version. It's been 24 hours and the mediafusion content is still old from few weeks ago. Doesn't refresh. Same with previous version 3.7.5. in Discord, someone said about multiple levels of cache running and it taking time. Not sure if we should wait further or if there is any tweaking to be done. Discussions in Reddit as well. No luck.

**Comment by mhdzumair** [comment]
> OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
>

Pushed a new commit to fix the curl error. Please pull the new docker container v3.8.0
