### ISSUE TITLE
ELF hosted addon is not scraping latest content

### ISSUE THREAD

**Issue by KarthiSurfer** [mhdzumair/MediaFusion#170]
1tamilmv and tamilblasters catalog is not updating to latest content even with the latest update

**Comment by karthikilan** [comment]
Same for me as well ...

**Comment by mhdzumair** [comment]
The scrapers are running now. It will work as expected.

**Comment by karthikilan** [comment]
> The scrapers are running now. It will work as expected. 

Thank you Sir. Yes, I see the updated content now.
