### ISSUE TITLE
SSL/mkcert issues

### ISSUE THREAD

**Issue by MarkBP99** [mhdzumair/MediaFusion#171]
Hi!

I'm trying to self-deploy using docker on my ubuntu vm.

I've gone through the tutorial, and have all docker containers running, however the nginx container keeps spewing ssl errors at me :)

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/04/16 20:33:16 [emerg] 1#1: cannot load certificate "/etc/ssl/certs/mediafusion.local.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/ssl/certs/mediafusion.local.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)

I've created the certifaces through mkcert as shown in the guide.

I'm not an expert, so i'm probably missing something very obvious...

Love your work!

**Comment by mhdzumair** [comment]
Ensure that the certificate file is correctly formatted. SSL certificate files should be in PEM format, which includes a header -----BEGIN CERTIFICATE-----, a footer -----END CERTIFICATE-----, and the Base64-encoded certificate data in between.

Also make sure the file permission in host os, if you're running linux the file permission might need 644

**Comment by MarkBP99** [comment]
Thank you for the quick answer!

How would i go about making sure the files are as they should be?

Both are formatted as pem files as standerd through mkcert.

Should i edit these files to contain the headers and footers after?

Maybe i'm using the ssl certs completely wrong? Should they be placed a specifc place or something?

Sorry for the noobish questions, and thank you again!

**Comment by mhdzumair** [comment]
Have you run 

```
mkcert -install

mkcert "mediafusion.local"
```

Make sure to run this command in the correct folder. This will create the mediafusion.local.pem file

**Comment by MarkBP99** [comment]
Yep, i did! in which folder?

**Comment by mhdzumair** [comment]
```
#Goto MediaFusion cloned repo
cd MediaFusion

# goto deployment/docker-compose
cd deployment/docker-compose

# then create the cert file
mkcert "mediafusion.local"

# Stop currently running compose if any and start
git pull
docker-compose -f docker-compose.yml down
docker-compose -f docker-compose.yml pull
docker-compose -f docker-compose.yml up -d

```

**Comment by MarkBP99** [comment]
I get this:

ERROR: failed to save certificate: open ./mediafusion.local.pem: is a directory

There are two directories named after the certs and keys already in the folder.

**Comment by MarkBP99** [comment]
@zJota Thanks for the help! I've re-done the install and have the certs and keys etc up and running.

@mhdzumair I'm able to locally access mediafusion.local on the host machine, and through the servers internal ip (192.168.1.27 etc) on my laptop on my network, however the main mediafusion container seems to be "unhealthy" and i just get an ERR_OPENING_MEDIA - Failed to fetch in Stremio.

Log from mediafusion container: 
INFO::20-Apr-24 14:29:42 - 192.168.1.23 - "POST http://192.168.1.27:8000/encrypt-user-data HTTP/1.1" 200
[2024-04-20 14:29:44 +0000] [10] [WARNING] Invalid HTTP request received.
[2024-04-20 14:29:44 +0000] [10] [WARNING] Invalid HTTP request received.

**Comment by mhdzumair** [comment]
@MarkBP99 pull the changes and test it with v3.8.1 image, the health check should be passed.

**Comment by mhdzumair** [comment]
Closing as Completed
