### ISSUE TITLE
Mediafusion(RD) chooses the wrong episode in some torrents

### ISSUE THREAD

**Issue by zJota** [mhdzumair/MediaFusion#174]
I'm using Mediafusion with RealDebrid, self hosted and with Torrentio enabled.
Here's an example where this occurs:

1- Search for Youjo Senki (series) and go for episode 1
![image](https://github.com/mhdzumair/MediaFusion/assets/12019360/f4db2821-4216-455a-9423-73407afdecab)

2- Choose [Erai-raws] Youjo Senki - 01 ~ 12 [1080p][Multiple Subtitle] (https://nyaa.si/view/1129748)
![image](https://github.com/mhdzumair/MediaFusion/assets/12019360/0edef4a6-0a98-49fc-a483-68b45687a6f4)

3- The episode that will play will be episode 11, check here https://real-debrid.com/downloads
![image](https://github.com/mhdzumair/MediaFusion/assets/12019360/8ae29e19-e8ca-45f9-82b5-cb9036cde4c3)

According to MediaFusion it was scraped by/from Torrentio, and choosing the same torrent with the Torrentio(RD) addon the correct episode plays.

**Comment by mhdzumair** [comment]
Issue has been fixed.
