### ISSUE TITLE
ERR_OPENING_MEDIA Failed to Fetch

### ISSUE THREAD

**Issue by mkrishnamoorthi** [mhdzumair/MediaFusion#176]
I am using docker for desktop on a windows machine for local deployment. mediafusion.local is accessible and when configured and installed, brings up the message "ERR_OPENING_MEDIA Failed to Fetch" in stremio. Prowlarr is setup properly and accessible at http://localhost:9696/. Attaching the container logs. Please let me know if you need more information. I tried configuring with just Direct Torrent and RD, both give the same error. 
In case this info is needed - the first 4 lines of .env file
```
HOST_URL="https://mediafusion.local"
MONGO_URI="mongodb://mongodb:27017/mediafusion"
REDIS_URL="redis://redis:6379"
PROWLARR_URL="http://127.0.0.1:9696"
```

Thanks for this awesome addon!
[Container Logs.txt](https://github.com/mhdzumair/MediaFusion/files/15048806/Container.Logs.txt)

**Comment by mhdzumair** [comment]
try to copy the installation link and open that link in browser to see whether you're getting addon manifest json. if so then past that link into stremio. 

from the log, i dont see any issue with mediafusion container, however the dramatiq worker container spawned several child workers.

**Comment by mkrishnamoorthi** [comment]
yes, the installation link brings up the manifest.json and providing it here. Pasting the link into stremio brings up the error - "Failed to Fetch"
```
{"id":"mhdzumair.addons.mediafusion","version":"3.7.5","name":"Media Fusion","contactEmail":"mhdzumair@gmail","description":"Universal Stremio Add-on for Movies, Series & Live TV. Source: https://github.com/mhdzumair/MediaFusion","logo":"https://mediafusion.fun/static/images/mediafusion_logo.png","behaviorHints":{"configurable":true,"configurationRequired":false},"resources":["catalog",{"name":"stream","types":["movie","series","tv"],"idPrefixes":["tt","mf"]},{"name":"meta","types":["movie","series","tv"],"idPrefixes":["tt","mf"]}],"types":["movie","series","tv"],"catalogs":[{"id":"mediafusion_search_movies","type":"movie","name":"Movies","extra":[{"name":"search","isRequired":true}]},{"id":"tamil_tcrip","type":"movie","name":"Tamil TCRip Movies","extra":[{"name":"skip","isRequired":false}]},{"id":"tamil_series","type":"series","name":"Tamil Series","extra":[{"name":"skip","isRequired":false}]},{"id":"hindi_hdrip","type":"movie","name":"Hindi HD Movies","extra":[{"name":"skip","isRequired":false}]}]}
```

**Comment by mhdzumair** [comment]
if this is working fine, then the issue is might be with ssl certificate trust error. make sure to run `mkcert -install` on host machine. 

Also, the current version of the addon is 3.8.1. pull the latest changes.

**Comment by mhdzumair** [comment]
also could you provide more information about your system, os, which deployment type etc?

**Comment by mkrishnamoorthi** [comment]
I pulled the latest and getting the same error. I am running on a Windows OS with WSL enabled and Docker Desktop on WSL mode. I had run mkcert -install using WSL and I can access https://mediafusion.local, which would mean that ssl is configured correctly, right?

**Comment by KarthiSurfer** [comment]
@mkrishnamoorthi are you trying to add the addon in your stremio desktop app or web app

**Comment by mkrishnamoorthi** [comment]
@KarthiSurfer I am adding to the desktop app

**Comment by mkrishnamoorthi** [comment]
Can you help with the URL to use to check. Also I noted in the original issue that these are the first 4 lines of the .env file. Do you see any issues with it?
```
HOST_URL="https://mediafusion.local"
MONGO_URI="mongodb://mongodb:27017/mediafusion"
REDIS_URL="redis://redis:6379"
PROWLARR_URL="http://127.0.0.1:9696"
```

**Comment by KarthiSurfer** [comment]
@mkrishnamoorthi run this command >> docker ps >> note down the container id >> then type docker logs containerID to get the logs for mongo db

**Comment by mkrishnamoorthi** [comment]
ok, so I made docker run on hyperv and redid all the steps, now I am able to install the addon. I am thinking it is because of how the SSL was setup in WSL that it did not work properly. I will experiment with WSL and update here. Closing the issue for now. Thanks for your time!

**Comment by mhdzumair** [comment]
As i mentioned, you need to trust self signed root certificates by your system. To do that you must need to run `mkcert -install` in your windows not in the wsl.
