### ISSUE TITLE
qbittorrent problem

### ISSUE THREAD

**Issue by Macer-cpp** [mhdzumair/MediaFusion#178]
I am trying to use mediafusion with a seedbox (rapidseedbox) to allow me to stream content. I linked it all with qbittorrent and webdav but when it comes to playing a torrent none of the content is showing in the qbittorrent however the media still plays (buffers quite a bit).

What might be causing this and what can I do to fix it?

**Comment by mhdzumair** [comment]
Its bit weird. You should be able to see the download in qbittorrent and even in the webdav storage. Otherwise it won't able to play anything. 

Could you share the ss for your configuration for qBittorrent-WebDav. Make sure to hide the credentials

**Comment by mhdzumair** [comment]
This is resolved right?
