### ISSUE TITLE
Playback error on PC and Android TV when using streams from streamed.su

### ISSUE THREAD

**Issue by FrancisFigueira** [mhdzumair/MediaFusion#180]
Hello there, 
So I have noticed that, when trying to use the addon to watch football or basketball trough links from the streamed.su source, I get a playback error on my stremio Windows app or my Android TV app, but not on my android phone app. Links from StreamBTW work fine in all the devices. 
I downloaded te addon from the elfhosted server.
Any reason known for it? 
Thank you very much for your time!

**Comment by mhdzumair** [comment]
As i mentioned in reddit post,

**Q: Why are live streams not working on Android TV, Windows, and web client of Stremio?** A: Currently, live streams are operational on Mac, Linux, Android, and Android TV v1.6.4. For Android TV users, you can download the app from this [link on Reddit](https://www.reddit.com/r/Stremio/s/4vyorqpspN). Additionally, we've logged a bug ticket with Stremio which you can track [here](https://github.com/Stremio/server-docker/issues/34).

**Comment by mhdzumair** [comment]
This issue need to be addressed from stremio team. I have mentioned the issue several time before. Also passed your message once again. 

https://discord.com/channels/667359689780101130/669087370334961664/1235033189932728442

**Comment by mhdzumair** [comment]
This will be fixed on next version of Stremio Android TV app, as well as the Windows

**Comment by FrancisFigueira** [comment]
Thank you so much for the follow up!

**Comment by 9acca9** [comment]
oh, im having the same problem. Cant see any stream in my android TV, but in my linux works perfect... the thing is i use my android tv almost always, the linux is just to make change in the configuration and things like that.
Thanks

**Comment by mhdzumair** [comment]
Its out of my hand, stremio team need to release a new version or you have to stick to v1.6.4

I even have added the support for DaddyLiveHD, however to work that stream, im waiting for stremio team to release a new version.

**Comment by drizzt09** [comment]
I am on 1.6.12 on my phone and no live tv channels work at all. 
They launch the player for a couple seconds then closes player to link options. 

All the link options seem to be same source.

**Comment by mhdzumair** [comment]
Its now supported via MediaFlow Proxy in v4.0.0
