### ISSUE TITLE
version 3.8.5

### ISSUE THREAD

**Issue by KarthiSurfer** [mhdzumair/MediaFusion#181]
please let us know when this version gets released in docker hub

**Comment by mhdzumair** [comment]
It has some changes for metrics endpoint and some config changes. That I have quickly released for elfhosted. Currently planning to release 3.8.6 with exciting update. Wait for the next proper release.

**Comment by mhdzumair** [comment]
Pro Tip: if you're curious to see the new stuff. Use the beta tagged image to try. :)

**Comment by KarthiSurfer** [comment]
thanks @mhdzumair, appreciate your work

**Comment by mhdzumair** [comment]
The latest version of 3.8.6 is now available.
