### ISSUE TITLE
Qbittorrent-webdav support for rdtclient

### ISSUE THREAD

**Issue by TheDabblingDuck** [mhdzumair/MediaFusion#184]
Hi,

I am trying to use rdt-client ( https://github.com/rogerfar/rdt-client ) with the qbittorrent-webdav functionality rather than actual qbittorrent and wondering if support for this could be added. Rdt-client is a wrapper for real debrid that works through the qbittorrent API but I suspect there are some API incompatibilities that are preventing it from working with MediaFusion's qbittorrent functionality. 

Right now after I add the configured mediafusion link to stremio, when I try to play a file it is never added to my self hosted rdt-client and I see a video message from mediafusion saying that the connection with qbittorrent has issues. For context, I am using the elfhosted mediafusion instance, and my rdt-client and webdav are publicly accessible through cloudflare tunnels.

My goal here is to basically proxy all content through a webdav on my home server so that real-debrid sees just one home IP rather than the IP of the device using stremio away from home.

Thanks!

**Comment by mhdzumair** [comment]
I and @funkypenguin (elfhosted) had this discussion on implementing this idea with their rtdclient and webdav. This will for sure give the multiple user access with different ips.

**Comment by TheDabblingDuck** [comment]
Looking forward to it - I hope it's compatible with the unmodified public version of rdtclient so self hosters like myself can use it too. Thanks for your efforts on this project!

**Comment by mhdzumair** [comment]
@TheDabblingDuck We have implemented new feature Proxy streaming. Which is streaming the content of streaming provider data via MediaFusion. This will solve your IP restriction issue. Not only limited to RealDebrid but also support all the streaming provider which supported in MediaFusion.

**Comment by mhdzumair** [comment]
Added support in v4.0.0 via MediaFlow
