### ISSUE TITLE
Catalog results override cinemeta data

### ISSUE THREAD

**Issue by sevbest** [mhdzumair/MediaFusion#187]
in Android TV version of stremio, the add-on strip / override the cinemeta data in the catalog for some cards, resulting in loss of imdb ratings or description for example.

**Comment by mhdzumair** [comment]
Stremio use first installed addon be data provider. MediaFusion provide description and metadata for imdb movies as well as adding imdb rating on movie poster.

**Comment by mhdzumair** [comment]
Any updates? I'm not quite understand your requirement.

**Comment by sevbest** [comment]
so if media fusion is installed on my stremio, the meta data of some movies
is overwritten in the catalog and I lose the imdb rating. it easy to see
and replicate if you browse through the default catalogs.

**Comment by sevbest** [comment]
Note that it appears to happen only with the Android TV version, the web
and desktop (macos) version appear unaffected.

**Comment by mhdzumair** [comment]
Got it. It's a bug/feature in Stremio Android TV. However, I can include the IMDB Rating from MediaFusion response, so that it will show again.

**Comment by sevbest** [comment]
Yeah that would be a good work around

**Comment by mhdzumair** [comment]
Done https://github.com/mhdzumair/MediaFusion/commit/ca18ff7efb6941b11491f9d25cc46a39fb1f5700
