### ISSUE TITLE
Subtitle addons

### ISSUE THREAD

**Issue by enko2974** [mhdzumair/MediaFusion#190]
Hello,thanks for this addon ,is very fast in finding results,but i have issues ,first issue is with every subtittle addon,exept embeded,it starts after 20 -30 seconds,and when it starts it stuuter the movie,then show desired language and stop the movie,second issue is that sometimes is freezing the hole system,google tv,android tv 12 with latest stremio version,and i have to pull the power cord to start again,thanks

**Comment by mhdzumair** [comment]
Duplicate https://github.com/mhdzumair/MediaFusion/issues/175, 

The issue has been fixed with v3.9.0
