### ISSUE TITLE
New Stremio Add-on Request

### ISSUE THREAD

**Issue by naveenland4** [mhdzumair/MediaFusion#20]
hello bro,

Have been enjoying with both your addons in Stremio. My request is now for all Serials and Shows.

If possible can you pls create an addon from https://www.tamildhool.net/ or https://tamilhdbox.com/

Thanks in advance.

**Comment by mhdzumair** [comment]
Sorry, no plan for scraping non-torrent websites.

**Comment by rubanrex** [comment]
@naveenland4 did you manage anything? I am interested in creating this add-on for tamildhool
