### ISSUE TITLE
Serialization error: expected value at line 1 column 1

### ISSUE THREAD

**Issue by yuviDX** [mhdzumair/MediaFusion#200]
I am getting this error when trying to install addon from elfhosted public and own deployed app from elfhosted as well. How to fix this?
![17163289147046336082498852642386](https://github.com/mhdzumair/MediaFusion/assets/44160525/f9e5c5ff-eedd-48f3-8d64-5ec15c22086f)

**Comment by mhdzumair** [comment]
I just checked the elf-hosted link, and it's working fine for me on a normal installation. However, in your case, I'm not sure what the error is.

I need the error logs. If you have a PC, open the developer network tab and follow these steps:
Could you try clicking on "Share installation URL" and then try to open that URL in a browser to see the error you're getting?

**Comment by mhdzumair** [comment]
This issue happens when a service container failed to response, after retry it will be okay.

**Comment by floralchemistry** [comment]
Still getting this error as well, tried clearing cache and re-entering 4 times now.
