### ISSUE TITLE
Premiumize links not working

### ISSUE THREAD

**Issue by Santaklawz** [mhdzumair/MediaFusion#201]
I am using the elfhosted version and it was working fine a week ago I reinstall the addon but no use authorize pm I get this error with premiumize ![image](https://github.com/mhdzumair/MediaFusion/assets/87282755/40477506-3963-4c5a-b599-f9f01b2a5c5a)

**Comment by mhdzumair** [comment]
hi @Santaklawz, Unfortunately I cannot look into older logs. Please join the TG group. I'll give you the access to a test server, so that I can look into the error you're facing.

**Comment by Santaklawz** [comment]
What is the tg link? Can you please test it on the elfhosted one with pm?

**Comment by mhdzumair** [comment]
Here is the TG link: https://t.me/mediafusion_stremio_addon

**Comment by mhdzumair** [comment]
Unfortunately, my PM subscription ended, so not able to test further. I can provide my own test link https://mhdzumair-mediafusion.elfhosted.com/ (password protected) DM me on tg. i'll provide the api_password to test and then when you do the testing i need to monitor the logs to find the error.

**Comment by mhdzumair** [comment]
Resolved in v3.9.3
