### ISSUE TITLE
API Exception occured.

### ISSUE THREAD

**Issue by casinoboy1** [mhdzumair/MediaFusion#207]
I get an API Exception occur when trying to stream something from the MediaFusion/Torbox add on in Stremio. Anyway you can help me fix it?

**Comment by mhdzumair** [comment]
I think its resolved with #204 lets see in the latest release. 

CC: @ragmehos

**Comment by claudiaas4** [comment]
Hi! I keep getting an API exception occurred when trying to stream Dexter from MediaFusion using RD on Stremio. Tried reinstalling and even refreshing my token. Any tips? TIA!
