### ISSUE TITLE
Qbittorrent Category

### ISSUE THREAD

**Issue by Made1908** [mhdzumair/MediaFusion#210]
Allow the User to set a Qbittorrent Category for the downloaded torrent. This would make the organization of the torrents much easier.

**Comment by mhdzumair** [comment]
You mean the Watchlist?  Like RD watch list etc?

**Comment by mhdzumair** [comment]
Could you provide the screen shot?

**Comment by mhdzumair** [comment]
how about setting category as "MediaFusion"?

**Comment by mhdzumair** [comment]
Like you want to provide the category value in addon config?
