### ISSUE TITLE
Add Torrents via file to enable support for private Trackers

### ISSUE THREAD

**Issue by Made1908** [mhdzumair/MediaFusion#215]
First of all really thank you for the great work. This addon is exactly what I was looking for for years to finally start using stremio.   

Now for my feature request:
Right now Torrents are added through a magnet link to the download client. 
This means that mediafusion only works with public trackers, because private trackers disable DHT/PEX and therefore the torrent gets stucked at searching for metadata.
To get mediafusion to work with private trackers the torrent needs to be added via the .torrent file. 
Prowlarrs api supports a flag 'privacy' to see if the indexer is private or public, so public trackers could still be added through the magnet link if you want to keep it that way.
Maybe for further reference Jackettio/Radarr/Sonarr already does it exactly that.

**Comment by mhdzumair** [comment]
I haven't used any private tracker on my own, need assistance over there. 

I have few questions
- "Added torrent via .torrent file" is it you want to add a torrent file data into mediafusion db? Or mediafusion need to provide you a torrent file?
- yes i recently set dht flag into the extraArgs in streams response. We can disable for private trackers. 
- are you plan to use the private tracker torrent with debrid provider or qbittorrent-webdav or stremio torrent engine?

**Comment by mhdzumair** [comment]
Added private & semi-private tracker torrent scraping support in 4.2.0
