### ISSUE TITLE
can any one help me to setup this file 

### ISSUE THREAD

**Issue by rajaaaaaaax** [mhdzumair/MediaFusion#217]
can any one help me to setup this file if yes give me discord or any thing were i can contact you

**Comment by mhdzumair** [comment]
Which file you want to setup?

**Comment by rajaaaaaaax** [comment]
Media Fusion Stremio Addon

**Comment by mhdzumair** [comment]
Its give both. You can join on our tg https://t.me/mediafusion_stremio_addon
