### ISSUE TITLE
API Exception occurred

### ISSUE THREAD

**Issue by Jamesd6** [mhdzumair/MediaFusion#222]
When searching for TV shows, all media fusion links are uncached and when clicking them, show the above error, "API Exception occurred". I have tried re-installing the add-on but still the same, none of the links play.
![Screenshot_20240701-161601](https://github.com/mhdzumair/MediaFusion/assets/174359424/7593aea8-8c47-4849-86c1-224aaea62323)

**Comment by mhdzumair** [comment]
what is the streaming provider service you're using?

**Comment by rjshrjndrn** [comment]
torrentio, prowlarr

**Comment by mhdzumair** [comment]
Its happened due to the RD server was down earlier. I can see its working back again.

**Comment by rjshrjndrn** [comment]
I think it'd be helpful to print a summary or the actual error message,  so that it'd not be a cliffhanger :grin:

**Comment by mhdzumair** [comment]
Yeah will handle this specific error.
