### ISSUE TITLE
Real debrid catalogue movie/series is not showing the files that are cached 

### ISSUE THREAD

**Issue by siva-kranthi** [mhdzumair/MediaFusion#224]
The real Debrid catalogue shows all the files that are there in my account. But when I open any file, it does not show the file that is already cached in my account like debris search add on

**Comment by mhdzumair** [comment]
Current implementation is fetching your torrent info hashes from your debrid account and match with our db data. so its only showing the catalog items which are in our db. when you open the movie its show all the available torrents. if the torrent is cached in real-debrid its show as ⚡️ 

im not sure what's your requirement is, do you want to highlight the already downloaded torrent in your specific account over the cached torrent in RD?

**Comment by siva-kranthi** [comment]
> im not sure what's your requirement is, do you want to highlight the already downloaded torrent in your specific account over the cached torrent in RD?

Yes. For some movies, it didn't show any results even when there is a cached file in my account

**Comment by mhdzumair** [comment]
Are you referring to catalog or streams?

**Comment by siva-kranthi** [comment]
I am talking about streams. Do both streams & catalogs work in the same way?

**Comment by mhdzumair** [comment]
Okay, if you're talking about the stream's cached indicator, that was happened due to RD down.
