### ISSUE TITLE
Torrent is not downloaded Yet  Please try Again 

### ISSUE THREAD

**Issue by jchacko-jr** [mhdzumair/MediaFusion#257]
Torrent is not downloaded Yet  Please try Again .
This issue is happening all over mediafusion streams .

**Comment by Neelgodly** [comment]
You need to wait for the torrent to download in your torrent download service

**Comment by mhdzumair** [comment]
Its based on the torrent seeders. You can find the details on the streaming provider ui. Ex: RD web page. 

Some torrents are showing as cached from RD API however when adding it, its stuck. This is mostly happening for very old torrents. 

From the mediafusion we can't do much on this.

**Comment by jchacko-jr** [comment]
Thanks for information 
@mhdzumair ☺️
