### ISSUE TITLE
4k torrents not showing up

### ISSUE THREAD

**Issue by vineethsankre** [mhdzumair/MediaFusion#266]
Hi Mediafusion team,

I’ve been using Stremio with Mediafusion RD to watch South Indian movies. Initially, TamilMV uploads torrents up to 1080p when a movie is digitally released. Mediafusion scrapes and adds these torrents to Stremio.

However, the problem arises when TamilMV later adds a 4K torrent. Unfortunately, Mediafusion doesn’t scrape the 4K torrents, so they don’t appear in the streams. As a result, I have to manually download them in RD.

Is there a way to ensure that 4K torrents are also scraped by Mediafusion?

Thanks,
Vineeth

**Comment by mhdzumair** [comment]
This will be supported on new version. its pending to release
