### ISSUE TITLE
Add filter by language (Spanish)

### ISSUE THREAD

**Issue by XDeadHackerX** [mhdzumair/MediaFusion#278]
Hello, I've been wanting to try MediaFusion for some time to scrape movies and series but my big limitation is the language, would it be possible to introduce a filtering by language and thus be able to select Spanish. Thank you.

**Comment by mhdzumair** [comment]
We have implemented the language sorting and filtering by selected languages. 

![SmartSelect_20240904_122120_Firefox](https://github.com/user-attachments/assets/66fa3ab2-4bf9-4b09-8fa0-e71e66217b92)

This will be available on next release.

**Comment by XDeadHackerX** [comment]
> Hemos implementado la clasificación y filtrado de idiomas por idiomas seleccionados.
> 
> ![SmartSelect_20240904_122120_Firefox](https://private-user-images.githubusercontent.com/44891939/364256531-66fa3ab2-4bf9-4b09-8fa0-e71e66217b92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzkwMTMsIm5iZiI6MTcyNTQzODcxMywicGF0aCI6Ii80NDg5MTkzOS8zNjQyNTY1MzEtNjZmYTNhYjItNGJmOS00YjA5LThmYTAtZTcxZTY2MjE3YjkyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA4MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OGIxZmQ4NWJmMDAxNTgxYjE0OGQwZmMwOGY1NDMzYWI5MTNlMmVhM2EwM2ZiZGNlYTRkNWI4MzNhYTE4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FpNAW5R8xgxKfksvQNfqkzsm0SraPJd7q8cDxNqt_N0)
> 
> Estará disponible en la próxima versión.

WoW, great job, I'll keep an eye out for the release of new update. Thank you very much 💪.
