### ISSUE TITLE
Option to choose category along with language

### ISSUE THREAD

**Issue by cg8440** [mhdzumair/MediaFusion#3]
Hi. Thanks for providing options to choose the language. However, it would be nice if we could choose category along with the language. For example, if I select tamil languaue, than I have all categories like Tamil HD movies, Tamil DVD-scr/HDcam, Tamil dubbed etc. I would like to select just Tamil HD movies and be able to hide all other Tamil categories. Same for other languages. I want to hide dubbed movies category and hdcam category. Is that possible? Thanks for all your time.

**Comment by mhdzumair** [comment]
Sure. I'll try to change the option to select preferred category types instead of language. Because there is limitation in the config customization since all the user select option is going to be part of the add-on URL and the URL having limited number of characters in different browser.
