### ISSUE TITLE
Source request 

### ISSUE THREAD

**Issue by ShankarKSH001** [mhdzumair/MediaFusion#308]
Tamil music site : https://masstamilan.dev/
Can you pls add this site

**Comment by mhdzumair** [comment]
I'm not interested in adding music into mediafusion for stremio at the moment in-fact this is https source.

**Comment by ShankarKSH001** [comment]
> I'm not interested in adding music into mediafusion for stremio at the moment in-fact this is https source.

Can you add for kodi seperate addon   pls you are the only tamil dev I seen

**Comment by mhdzumair** [comment]
Sorry for now I'm not interested on that, since there are so many other way of listing music like YouTube music, Spotify etc (with mods)
