### ISSUE TITLE
Create docs README regarding the RealDebrid

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#32]
## Description

As a maintainer, I would like to add a short description about RealDebrid service under `streaming_providers/realdebrid/README.md`  Also add the referral link 

```
<a href="http://real-debrid.com/?id=9490816" title="Real-Debrid"><img src="http://real-debrid.com/static/images/banner/en.png" /></a>
```

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.
