### ISSUE TITLE
 Add country flags

### ISSUE THREAD

**Issue by XDeadHackerX** [mhdzumair/MediaFusion#326]
It would be possible to modify the Torrent Stream Display option to add as many flags as languages the Torrent has. I think it would be beneficial to recognize more easily the languages of the Torrent, especially when the couch is far from the TV, and it would also follow the same pattern as the rest of Addons. Thank you very much.

**Comment by XDeadHackerX** [comment]
> For usual language it would be fine, however there are many languages in India so it's not good to differentiate. Maybe we could have a configuration to show either language name or country emoji.

I understand, I had once heard about the language problem in India. It would be a very good idea to make this part of the configuration, making MediaFusion a very very very customizable Addon from the configuration menu.

Thank you for supporting the idea.

**Comment by Arshit-Singhal-Official** [comment]
I would like to contribute on this

**Comment by mhdzumair** [comment]
Thanks buddy, :crossed_fingers:

**Comment by mhdzumair** [comment]
![image](https://github.com/user-attachments/assets/1b89ab87-07d4-4b9e-8183-8c7c56c8f0d6)

**Comment by XDeadHackerX** [comment]
> This is now available in v4.3.0. Goto Pro mode -> Torrent Stream Display option -> Select "Show Language Country Flag" 

Thank you very much for considering this request 🙏🏼❤️.
