### ISSUE TITLE
MediaFusion is down.

### ISSUE THREAD

**Issue by Akhilmp91** [mhdzumair/MediaFusion#33]
Unable to fetch anylink in Stremio.

**Comment by mhdzumair** [comment]
If you would like to setup it up locally please follow the https://github.com/mhdzumair/MediaFusion#hammer_and_wrench-development

**Comment by mhdzumair** [comment]
Seems like some other add-on developer also faceing server downtime with stremio beamup nodes https://github.com/Stremio/stremio-addon-sdk/issues/242

**Comment by KARANRSB** [comment]
Hi bro The addon works fine now thanks for all the updates and also please
add it to the netlify addons of the main stremio community curated addons
so that other people can find it as well

**Comment by KARANRSB** [comment]
And also give the media fusion addon the tag of debrid support on that
website like how torrentio and other addons have that time more people may
use it 👍

**Comment by mhdzumair** [comment]
Thanks for the confirmation @KARANRSB
