### ISSUE TITLE
Add on not working with kodi 20.3 ios

### ISSUE THREAD

**Issue by Harishwarrior** [mhdzumair/MediaFusion#343]
Tried to install this from zip

2024-11-03 20:30:35.894 T:818042    
info <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2024-11-03 20:30:41.590 T:840283   error <general>: CAddonInstallJob[plugin.video.mediafusion]: The dependency on inputstream.ffmpegdirect version 20.5.0 could not be satisfied.

**Comment by mhdzumair** [comment]
What is the ffmpegdirect latest version available in ios? This is not a hard dependency, you can unzip the file and then open the addon.xml to update the available version of ffmpegdirect addon thart provided from official repository. 


Also note that, this addon is tested only on kodi omega v21

**Comment by Harishwarrior** [comment]
> What is the ffmpegdirect latest version available in ios? This is not a hard dependency, you can unzip the file and then open the addon.xml to update the available version of ffmpegdirect addon thart provided from official repository.
> 
> Also note that, this addon is tested only on kodi omega v21

I actually updated to the latest. The addon is installed fine. Elementum addon won't work in iOS. So, my best bet is a debrid account with Kodi.. and

Is there is any possibilities of adding direct streaming links instead of torrents in future?? An separate add on maybe

**Comment by mhdzumair** [comment]
Nope atm. You can use any free streaming provider services like seedr.
