### ISSUE TITLE
Request to Implement Proxy System for Scrapers (Including Torrentio)

### ISSUE THREAD

**Issue by PaulGitProject** [mhdzumair/MediaFusion#347]
Hello!

As requested after our discussion, I’m creating a ticket regarding the implementation of a proxy system for scrapers (including Torrentio).

It would be great to have this system in place to prevent 403 Forbidden results from Torrentio.

Thanks in advance!

**Comment by mhdzumair** [comment]
This is available now. you can set `requests_proxy_url`
