### ISSUE TITLE
Extension unusable

### ISSUE THREAD

**Issue by DenuxPlays** [mhdzumair/MediaFusion#352]
Hey,

Since the Update the Extension is unusable.
Its loading indefenitly

**Comment by mhdzumair** [comment]
Is it for kodi?

**Comment by DenuxPlays** [comment]
No for stremio

**Comment by mhdzumair** [comment]
The update has still not been applied to the mediafusion public host yet. Are you using private instance or elfhosted public version?

**Comment by DenuxPlays** [comment]
Yeah you are Right i am still on 4.1.3
I am using the public instance

Already Tried some basic debugging stuff

**Comment by mhdzumair** [comment]
We're having high load on medisfusion elfhosted public server. :). Will resolve the issue soon.

**Comment by DenuxPlays** [comment]
Great to hear 

Would selfhosting help?
I saw that a Docker Image is available so could this solve my issue?

**Comment by DenuxPlays** [comment]
Thank You for your fast reply btw

Really appreciate it

**Comment by mhdzumair** [comment]
Yes, you can do the selfhosting of mediafusion completely locally or servers checkout the deployment folder, or else you can get the elfhosted private mediafusion pod. However, note that the elfhosted use 1 mongodb pod, which is common for public and private pods. So the main issue is relying on the high usage of the db. We planned to migrate the db to cluster based pods. I think it's time to do that ASAP.

**Comment by mhdzumair** [comment]
Here is the localhost guide https://video.elfhosted.com/w/rgRFCmdgWW2HDES4QSD6Kb

**Comment by DenuxPlays** [comment]
got it working kinda

I've been getting these error messages:
![image](https://github.com/user-attachments/assets/81fc01fb-7360-4739-a35b-87a0c429d50b)

I am not quite sure why mediafuchs is relying on torrentio?

**Comment by DenuxPlays** [comment]
Also I have another question.

When `prowlarr-indexers.json` is updated should I also execute the `setup-prowlarr.sh` script again?

**Comment by Tenessy** [comment]
Hey ! I've processed successfully the Docker installation to have mediafusion locally but Stremio don't find this Addons when i want to watch a serie or a movie.

<img width="413" alt="Capture d’écran 2024-11-14 à 12 25 04" src="https://github.com/user-attachments/assets/0089de02-df3b-48fe-acbf-d4a6736313ef">
<img width="615" alt="Capture d’écran 2024-11-14 à 12 24 40" src="https://github.com/user-attachments/assets/44f7a2a4-634a-4905-8fa9-4510a28d660d">

**Comment by mhdzumair** [comment]
> I am not quite sure why mediafuchs is relying on torrentio?

It's not rely on torrentio. You can disable the torrentio scraping in the env if it's not working. The latest version include more scrapers, such as scraping from other mediafusion deployments.

**Comment by mhdzumair** [comment]
> When `prowlarr-indexers.json` is updated should I also execute the `setup-prowlarr.sh` script again?

No need to set up it again every time, you can goto prowlarr url directly and add your preferred indexers.
