### ISSUE TITLE
Cannot get to run with existing traefik network

### ISSUE THREAD

**Issue by VenomousRage** [mhdzumair/MediaFusion#357]
I have followed all of the steps at: https://github.com/mhdzumair/MediaFusion/blob/main/deployment/docker-compose/README.md. I have mediafusion up and running locally, but cannot add it to my traefik network. I attempted to add a rule in my traefik config.yml, like I have done for 30+ other servives, but when I do, my custom domain name is NOT accessible. Any guidance would be appreciated.

**Comment by Telkaoss** [comment]
I had the same issue with Traefik. Remove

healthcheck:

from the compose.yaml, for some reason, Docker stays in the "starting" state and doesn't work, and the Traefik redirection also doesn't work.

**Comment by VenomousRage** [comment]
@Telkaoss Thank you for this. It worked like a charm!
