### ISSUE TITLE
Stream link template not show full file name so Trakt API and OpenSub not work on external player

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#368]
Stream link template not show full file name so Trakt API not work on external player

Exp:
https://mediafusion.elfhosted.com/streaming_provider/*Masked*/stream?info_hash=8fbb150d8ba97e2f044117d8046b77d86263cbe5&season=1&episode=6

https://mediafusion.elfhosted.com/streaming_provider/*Masked*/stream?info_hash=937d1159102309d8b0b8b9470599fe5e9ad02e31&season=1&episode=6
Basically now the external player will get the Video file name as stream.
Exp:
Infuse & IINA need file name have template like this
https://hkg1.download.real-debrid.com/d/XXXX/Monsieur.Spade.S01E02.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb%5BEZTVx.to%5D.mkv
This is a direct link from real-debrid.

This new template from the Stremio- Jacket which work with Trakt now.
Original he had the similar stream link template like you ( I also the one reported this issue with him)
![CleanShot_2024-02-25_at_17 08 42](https://github.com/user-attachments/assets/6df83756-dc82-4ba9-8d98-807a30e14df9)

This one is from torrentio which worked as well ( IMO still the best option- the one I cover is a string which had my API token for Real-Debrib)
![CleanShot_2024-02-25_at_17 13 30](https://github.com/user-attachments/assets/7c83a663-dc04-4d8d-a4c7-484803d0d223)

By: @olivergiangvu

**Comment by mhdzumair** [comment]
@olivergiangvu i deleted your original post due to its expose your RD token in MediaFusion Link. so dont post your config link in a public forum. Make sure to reset your RD OAuth code and private key.

**Comment by mhdzumair** [comment]
I believe this issue is due to this bug https://github.com/Stremio/stremio-web/issues/720 ?

**Comment by olivergiangvu** [comment]
> I believe this issue is due to this bug [Stremio/stremio-web#720](https://github.com/Stremio/stremio-web/issues/720) ?

After read through this bug, I think this not 100% related.

The main thing come from how player use metadata to scrobble Trakt API and search for Subtitle with OpenSub API.

For Infuse/IINA they limited on File Name  and URL only so on the Stream URL need to have these thing in order for them to recognize the metadata - and it should be at the last string of the URL ( based on all my testing so far).

All other addon  that fixed toward that direction wil result a perfect scrobbling when passing URL from Stremio/Kodi/Vidi/ Streamer App to external players.

**Comment by mhdzumair** [comment]
MediaFusion is not working like this. As you know, the recent debrid changes removed the instant availability endpoint which those addon used to fetch the file data prior to user open a stream. however the MediaFusion took a different approach since it will be downloading once the user start to play that stream. 

These url are redirect url. So redirector will resolve the RD link. Why isn't those players are implemented based on the final url?

**Comment by olivergiangvu** [comment]
> MediaFusion is not working like this. As you know, the recent debrid changes removed the instant availability endpoint which those addon used to fetch the file data prior to user open a stream. however the MediaFusion took a different approach since it will be downloading once the user start to play that stream.
> 
> These url are redirect url. So redirector will resolve the RD link. Why isn't those players are implemented based on the final url?

I don't know technical enough from the player side but seem that the limitation currently for Infuse/IINA.

They can only extract the media/file name from the x-callback URL to match with Trakt and TVDB metadata

https://community.firecore.com/t/pass-metadata-details-via-x-callback-url/51278
https://support.firecore.com/hc/en-us/articles/215090997-API-for-Third-Party-Apps-Services

For IINA - based on an external. scrobbler. for Trakts https://github.com/iamkroot/trakt-scrobbler

And also the similar way like Infuse to get metadata for the Sub searching process.

**Comment by mhdzumair** [comment]
Added support for showing the video file name in the URL. 
![image](https://github.com/user-attachments/assets/e8818a0a-71ea-40ad-93cd-53d58697444f)


Note that the name of the video will only be included if mediafusion already knows about it. Otherwise, it won't be included. Then someone start to play that torrent via file data trusted debrid services like RD then the file name get updated so the next time it will be shown.
