### ISSUE TITLE
Update the stremio addon to v3.4.0

### ISSUE THREAD

**Issue by johnnyw94** [mhdzumair/MediaFusion#38]
It's still showing the older release version

![Screenshot_2023-10-30-13-22-01-329_com.stremio.one.jpg](https://github.com/mhdzumair/MediaFusion/assets/36622355/50ed9698-bf68-41d4-a6c5-39c579dfe504)

**Comment by mhdzumair** [comment]
The stremio's beamup server behave strangely. When I do the deployment, it reflects changes after several weeks. join the tg group for getting beta link.

**Comment by johnnyw94** [comment]
> The stremio's beamup server behave strangely. When I do the deployment, it reflects changes after several weeks. join the tg group for getting beta link. 

Thanks for the reply. I'll do that!

**Comment by mhdzumair** [comment]
Use this link: https://882b9915d0fe-media-fusion.baby-beamup.club/
