### ISSUE TITLE
Request: HDR tags

### ISSUE THREAD

**Issue by Blissingg** [mhdzumair/MediaFusion#380]
Would it be possible to add the HDR type to the parsed data?

Right now its not possible to use that option and know which HDR type is being provided, HDR10, HDR10Plus or DV.

Samsung TV users won't have a good time when they accidentally load streams that are Dolby vision.

The rest of us would prefer to use DV when available over all other formats.

**Comment by aptalca** [comment]
I'd like to echo that request. I have a 4k tv with faux hdr (it accepts HDR10 input but cannot really display hdr)
There are also issues with some of the new combo hdr formats where the ripper includes both HDR10+ and DV, and some players like the fire tv cannot display them properly, resulting in a black screen with just audio.

Torrentio is able to recognize and filter out hdr formats, which I do in its settings so I only get 4k SDR listed in results. It does a surpridsingly good job. It would be really nice to be able to do that in MF as well.

**Comment by jishnurk** [comment]
> Would it be possible to add the HDR type to the parsed data?
> 
> Right now its not possible to use that option and know which HDR type is being provided, HDR10, HDR10Plus or DV.
> 
> Samsung TV users won't have a good time when they accidentally load streams that are Dolby vision.
> 
> The rest of us would prefer to use DV when available over all other formats.

+1!

**Comment by AdrianG-OSS** [comment]
This would be my number 1 request as well (probably the main reason I still keep Torrention arround). Having sepparate tages for HDR10, HDR10+ abnd DolbyVision would be very helpful. Another nice thing would be to replace the confusing tags for the dts audio files, DTS lossless and DTS Lossy with the name of the codecs, DTS and DTS MasterAudio. For Dolby we have Dolby Digital, Dolby Digital Plus and Dolby TrueHD. I don't see why DTS can't follow the same naming convention.

**Comment by mhdzumair** [comment]
![image](https://github.com/user-attachments/assets/bd141b1b-8c30-40db-827b-49873bead947)
