### ISSUE TITLE
Ability to feed Media Fusion Scraper the file IDs of manually uploaded RD & AD files

### ISSUE THREAD

**Issue by BRKsays** [mhdzumair/MediaFusion#388]
Sometimes some files are not available in cache. For that Media Fusion Scraper is a great tool. But there is no option to specify self uploaded content except torrent links.

I tried uploading a movie via gdrive to RD and AD. Media Fusion never picked it up even though I renamed the file according to the movie title.

To enhance user contributions for obscure files, please let us specify the RD and AD file IDs to Media Fusion Scraper so that it updates result for the same.

**Comment by mhdzumair** [comment]
No plan for adding such feature specific to RD. Now, MediaFusion supports importing WebSeed torrents. Which you can create the torrent file with any static URL.
