### ISSUE TITLE
Results in other languages

### ISSUE THREAD

**Issue by XDeadHackerX** [mhdzumair/MediaFusion#393]
Hello Mhdzumair,

It's been a while since I've commented here, as this Addon continues to grow at breakneck speed but without deteriorating any of its old features. 

Unfortunately since a few days ago something changed, as a Spanish user, I have MediaFusion configured only in Spanish, but in recent days I started to get torrents that are not categorized with a language and that caused problems in the use of this Addon, making it uncomfortable to choose between so many torrents which only the first ones are in my language. 

I would appreciate if you could put it back to the way it was before, in which only results with the selected language appeared. Thank you very much for continuing to improve this addon day by day.

Best regards.

**Comment by mhdzumair** [comment]
Fixed on https://github.com/mhdzumair/MediaFusion/commit/3b22ff175391b62bccd33b1fdd6af81b343c5a01

**Comment by XDeadHackerX** [comment]
It works!!! Thank you very much.
