### ISSUE TITLE
Is it possible to access .torrent files or magnet links from video links?

### ISSUE THREAD

**Issue by binuengoor** [mhdzumair/MediaFusion#395]
I'm wondering if there's a way to grab the .torrent files or magnet links for videos on Mediafusion. Sometimes I prefer to download copies of movies and shows to add to my Plex server for friends and family to watch. Mediafusion catalogue is perfect for my usecase.

**Comment by mhdzumair** [comment]
You can use "Download via Browser" feature to download the content. Or you can grab the info hash and trackers in the API response, see the API docs under /docs page of MediaFusion deployment. But there is no endpoint for .torrent file generation
