### ISSUE TITLE
Add support for alternative title searching

### ISSUE THREAD

**Issue by victorgveloso** [mhdzumair/MediaFusion#401]
Some indexers in jackett and prowlarr benefit from translated title searching. For instance, Brazilian websites have their movies and TV shows named in Brazilian Portuguese. 

Since mediafusion already scrape IMDb/tmdb meta and match titles for filtering, it should be possible to leverage such data for searching.

This issue formalizes [a feature request made in Reddit](https://www.reddit.com/r/StremioAddons/s/BcnA2kefsF)

**Comment by mhdzumair** [comment]
Added support for scraping with AKA titles in 4.3.0
