### ISSUE TITLE
Feature request: New streaming provider AllDebrid

### ISSUE THREAD

**Issue by asaddon** [mhdzumair/MediaFusion#41]
Please add AllDebrid

Website - https://alldebrid.com/
API docs - https://docs.alldebrid.com/#general-informations

**Comment by mhdzumair** [comment]
@asaddon are you able to help to test the alldebrid integration? If so, please join the TG group & ping me. 
Thanks.

**Comment by asaddon** [comment]
> @asaddon are you able to help to test the alldebrid integration? If so, please join the TG group & ping me. 
> 
> Thanks. 

Done.
