### ISSUE TITLE
Unable to authorize Real-Debrid from addon configuration page

### ISSUE THREAD

**Issue by shscs911** [mhdzumair/MediaFusion#42]
* Unable to authorize Real-Debrid from addon configuration page.
* After clicking the `Authorize with Realdebrid` button, the following error pops up.

![Screenshot_20231113_154604](https://github.com/mhdzumair/MediaFusion/assets/44034402/bac84334-a300-464b-9a0f-0d410f30f5a8)

* Network logs show a Gateway Timeout for the `get-device-code` API (https://882b9915d0fe-mediafusion.baby-beamup.club/realdebrid/get-device-code)

 ![Screenshot_20231113_155103](https://github.com/mhdzumair/MediaFusion/assets/44034402/3100b65c-48d1-4786-8c80-a7f0acc47405)

**Comment by mhdzumair** [comment]
hi @shscs911. The main server is down. Please use this url https://882b9915d0fe-media-fusion.baby-beamup.club/configure

**Comment by mhdzumair** [comment]
The Main link is working now with the new release

**Comment by shscs911** [comment]
Thanks for fixing it quickly, man. Much appreciated.
