### ISSUE TITLE
Real Debrid Ivalid Token Error

### ISSUE THREAD

**Issue by sunilcab70** [mhdzumair/MediaFusion#44]
I installed the add on after copy pasting my token link, stremio then poplulates all the real debrid link when I select one it shows invalid token. Same token is working just fine everywhere else including Torrentio.

**Comment by mhdzumair** [comment]
Hi @sunilcab70 MediaFusion doesn't use your **Private Token**. Please try to click on Authorize button for creating OAuth token which is having restricted permissions.

**Comment by sunilcab70** [comment]
Thank you that worked
