### ISSUE TITLE
Feature Request: Filtering and Sorting by qualities and size

### ISSUE THREAD

**Issue by MrMonkey42** [mhdzumair/MediaFusion#47]
Similar to Torrentio, I would like to have Filtering and Sorting options by qualities and size. These options can be specified by the user when installing the addon.

Example: I have a 4k TV and I only want MediaFusion to show streams in atleast 1080p quality.

**Comment by mhdzumair** [comment]
Added the resolution filtering and sorted by size. 
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/61e28604-bc40-4607-acd3-ff1427238808)
