### ISSUE TITLE
Real Debrid invalid token while accessing content

### ISSUE THREAD

**Issue by rijoymanghat** [mhdzumair/MediaFusion#51]
Have tried both ways api and authorizing. While trying to access content it says invalid token. The api is correct as I use the same for others and it works fine there.

**Comment by mhdzumair** [comment]
Hi @rijoymanghat are you still facing the error?

**Comment by rijoymanghat** [comment]
@mhdzumair thanks much for checking back and sorry to not report back. I tried what you said and this time it worked fine. Thanks again !
