### ISSUE TITLE
Feature request: Add option to include Real Debrid

### ISSUE THREAD

**Issue by SanthoshAnbalagan** [mhdzumair/MediaFusion#54]
Please add Real Debrid as debrid provider

Website : https://real-debrid.com/
API docs : https://api.real-debrid.com/

Thanks in advance.

**Comment by mhdzumair** [comment]
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/4c4bd080-32c3-43b3-9577-cac11dc45624)
real-debrid is available.

**Comment by SanthoshAnbalagan** [comment]
Thanks Bro, appreciate your prompt response❤
