### ISSUE TITLE
AllDebrid Servers are not allowed

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#58]
# Description
As a developer, I want to fix the AllDebrid API error when using it with production server. The AllDebrid working perfectly in local when running the add-on locally. But using it with server then getting following error. 
```
ERROR::26-Dec-23 16:27:25 - Exception occurred: Failed to add magnet link to AllDebrid {'status': 'error', 'error': {'code': 'NO_SERVER', 'message': "Servers are not allowed to use this feature. Visit https://alldebrid.com/vpn if you're using a VPN."}}
```

**Comment by mhdzumair** [comment]
@MrMonkey42 I see you have integrated the alldebrid in your add-on. Any idea on this error?

**Comment by mhdzumair** [comment]
Implementation PR https://github.com/mhdzumair/MediaFusion/pull/55

**Comment by mhdzumair** [comment]
Update: I think that AllDebrid has IP-based detection. it's even detected as server access when I try to use API for adding magnet in a fresh EC2 server with only SSH service that allows only for my local IP.

**Comment by MrMonkey42** [comment]
@mhdzumair My addon doesn't actually have any functionality to add new magnet links. It only reads existing files already downloaded in the cloud.

However, Torrentio does add new magnets to AllDebrid.

https://github.com/TheBeastLT/torrentio-scraper

**Comment by mhdzumair** [comment]
Getting user's torrent API `/magnet/status` is working. But it won't allow `/magnet/upload` for adding a torrent.

**Comment by mhdzumair** [comment]
> However, Torrentio does add new magnets to AllDebrid.

Yes. I was desperate to hear about his secret sauce. I have gone through his code implementation, which is not fancy. But they deployed the service on their own servers. 

My assumption is, Either that server IP address is not get detected or AllDebrid whitelisted it.

**Comment by asaddon** [comment]
![image](https://github.com/mhdzumair/MediaFusion/assets/21283991/b8883ea4-1315-4d72-b17f-469bda7536a6)

As expected, I believe client-side API calls is the key and it's highly likely Torentio is doing the same thing.

**Comment by mhdzumair** [comment]
They restrict the add magnet API endpoint. But the other endpoint seems to be working. So I'm thinking of redirecting the add magnet endpoint from stremio. So that it will run the API call from local. But I think it might give video error on first try and then second call will respond it from server. 

I'll try this method.

**Comment by mhdzumair** [comment]
its not only download the magnet. but also the link unlock endpoint also not allow it to be run in the server. the only way is to use the alldebrid is from local addon or using local redirector for atleast to parse the unlock link. i have setup a minimal repo https://github.com/mhdzumair/alldebrid-redirector. at minimum you need to setup this in your local and then you can use alldebrid with stremio.  

is it possible to run a python script in your local? if so i can proceed the further development to add local redirector service link in the main addon config page. otherwise it wast of energy to focus more on this specific problem.

**Comment by nityanantan23** [comment]
Is the problem fixed omor does it have workaround for alldebrid.

**Comment by mhdzumair** [comment]
@nityanantan23 for now, you need to set up the addon in local to work with alldebrid.

**Comment by nityanantan23** [comment]
@mhdzumair can I have a step by step guide on how to run it locally

**Comment by mhdzumair** [comment]
here is the detailed guideline to setup the MediaFusion easily https://github.com/mhdzumair/MediaFusion/blob/develop/deployment/README.md
