### ISSUE TITLE
No links when searching older movie/series

### ISSUE THREAD

**Issue by TheKidRock** [mhdzumair/MediaFusion#7]
Hi, I have installed your addon as well as installed almost all addons on Stremio. However, when I search for any show, there are no links displayed. 
For eg, I was searching "The Kapil Sharma Show" which is available on your website but on Stremio, I do not get results from your addon or other addons.
Screenshot here: https://imgur.com/a/jjMYPlL
Two links shown in the screenshot above, they do not play. Why am I not getting more links for the show, either from your addon or from other addons? If I search for English movies, then I do get lots of links.
Can you please suggest any solutions? Thanks.

**Comment by mhdzumair** [comment]
Scraping movies & streams from a search keyword functionality was added into scrapper code. If you're setting up in local add-on then you can scrap the movies & series. See the commands details in [scrappers's README](https://github.com/mhdzumair/MediaFusion/blob/main/scrappers/README.md)
