### ISSUE TITLE
Move site links to config to avoid blocks

### ISSUE THREAD

**Issue by vijayvcm** [mhdzumair/MediaFusion#71]
Hi @mhdzumair,

Thanks for your awesome work.

I just have some suggestions on storing the links.

I see that you have hard-coded the links inside the scrapper folder. It might be a problem if the sites change their domain or get blocked.

I would suggest keeping it in the config file separately and referring directly to the scrapper file.

Also, you can use the https://unblockit.pages.dev/ website to get the unblocked website directly.

**Comment by mhdzumair** [comment]
You're welcome to make the contribution. The changes will be done in the future if not.

**Comment by vijayvcm** [comment]
I would like to contribute but I am not familiar with python (can understand the logic though). I am more familiar with .NET and Nodejs. I will try if I can contribute in any areas.

Let me know if you need any help in the above mentioned technologies. Happy to help ✌🏻
