### ISSUE TITLE
Seedr.cc

### ISSUE THREAD

**Issue by jeemitsha** [mhdzumair/MediaFusion#78]
Nice to see you added seedr.cc to the addon, but how do we delete existing file ? And also I can see the video been downloaded on seedr.cc and in wishlist but not able to play it from stremio application on Android.

**Comment by mhdzumair** [comment]
Regarding the seedr stream issue in android, see this issue for more information https://github.com/Stremio/stremio-bugs/issues/651

For now use external player. 

To delete any files, you can do it on seedr web ui.  The addon doesn't delete the seedr folder when you're finish watching a movie. 

The addon only will take care of automatic cleanup when you need to watch another movie.

**Comment by mhdzumair** [comment]
The issue has been fixed by removing the '[]' characters and unsupported character in the filename so that the URL is now working in the Android Client. https://github.com/mhdzumair/MediaFusion/commit/30907a07251800bcd9521a8dbf35f3bd61eec335

**Comment by jeemitsha** [comment]
> The issue has been fixed by removing the '[]' characters and unsupported character in the filename so that the URL is now working in the Android Client. https://github.com/mhdzumair/MediaFusion/commit/30907a07251800bcd9521a8dbf35f3bd61eec335

Nice 🙂
