### ISSUE TITLE
Cannot configure the Addon

### ISSUE THREAD

**Issue by Drjacky** [mhdzumair/MediaFusion#79]
In the config [page](https://882b9915d0fe-mediafusion.baby-beamup.club/configure). after I select what I want, when I click the Install Addon button, nothing happens!
<img width="676" alt="Screenshot 2024-01-14 at 13 30 54" src="https://github.com/mhdzumair/MediaFusion/assets/2296754/e16a7bb3-23f2-4e8c-b03d-09ec339d05f2">

**Comment by Drjacky** [comment]
This helped me to configure the addon for now: https://github.com/mhdzumair/MediaFusion/issues/42#issuecomment-1807940412

**Comment by mhdzumair** [comment]
@Drjacky please check now. The stremio server was down. I have redeployed.
