### ISSUE TITLE
Enhanced the MediaFusion Logo

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#8]
As a maintainer, I would like to improve the design of new logo / modify the current logo design to better visualization. 

## Acceptance Criteria
- Design can be simple & visually appealing
- Clear fonts size and readability of text
- A graphical element design
- Output logo PNG & SVG file for reproducing the logo 

## Artifacts
- [SVG file](https://github.com/mhdzumair/MediaFusion/blob/main/resources/images/mediafusion_logo.svg)
- [PNG file](https://github.com/mhdzumair/MediaFusion/blob/main/resources/images/mediafusion_logo.png)

**Comment by Ahzem** [comment]
Assign me
