### ISSUE TITLE
More torrent sites?

### ISSUE THREAD

**Issue by jeemitsha** [mhdzumair/MediaFusion#81]
Can we add more torrent website like torrentio ? Also torrentio doesn't support seedr.cc so having these here can use seedr.cc for it.
The once below ?
YTS(+), EZTV(+), RARBG(+), 1337x(+), ThePirateBay(+), KickassTorrents(+), TorrentGalaxy(+), MagnetDL(+), HorribleSubs(+), NyaaSi(+), TokyoTosho(+), AniDex(+), Rutor(+), Rutracker(+), Comando(+), BluDV(+), Torrent9(+), MejorTorrent(+), Cinecalidad(+).

**Comment by mhdzumair** [comment]
We can add. If someone is going to create the scrapping script for those sites one by one.

**Comment by jeemitsha** [comment]
> We can add. If someone is going to create the scrapping script for those sites one by one. 

Ok make sense, I beleive what torrentio has is in javascript, so it's not recommended by making a different node API to use with mediafusion just a thought 💭

**Comment by mhdzumair** [comment]
You mean to use their resources within this addon?

**Comment by mhdzumair** [comment]
Thank you for the idea. We can implement that easily. Since Torrentio doesn't offer Seedr and PikPak integration, there may be many users who want to watch without using paid debrid services.

The only problem I'm having is with the limited server resources in the Streamio Beamup free service. Lately, I have had to restart the deployment quite frequently. Unless the Streamio team provides more usage metrics, I'm unable to identify the root cause of this issue. Other options include having users self-host the addon or someone to provide a higher infrastructure for hosting it.

**Comment by jeemitsha** [comment]
> Thank you for the idea. We can implement that easily. Since Torrentio doesn't offer Seedr and PikPak integration, there may be many users who want to watch without using paid debrid services.
> 
> The only problem I'm having is with the limited server resources in the Streamio Beamup free service. Lately, I have had to restart the deployment quite frequently. Unless the Streamio team provides more usage metrics, I'm unable to identify the root cause of this issue. Other options include having users self-host the addon or someone to provide a higher infrastructure for hosting it.

oh yeah that totally makes sense, lets see if it would be possible in near future 

or can add a payment gateway for small fees like 50rs a year only for other torrent providers and see if enought people want it then can add up to get a server maybe, 

ha ha just one more idea, like the money accmulated can be added up and displayed on web with target amount, if by a certain day the target is not acheived then the money goes as refund 🤐

i know this might be too much of work of a side hsutle 😅

**Comment by jeemitsha** [comment]
Yo thanks for working on my suggestion 😁

Its going to be great now, maybe soon number 1 stremio addon 😍

**Comment by mhdzumair** [comment]
Ill add the scrapping functionality for series as well.

**Comment by mhdzumair** [comment]
> Ill add the scrapping functionality for series as well.

Added support for scraping series from torrentio ✅
