### ISSUE TITLE
Add support to find seeders/peers count and update db in schedule service

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#86]
As a developer, I would like to add the functionality to query the current available seeders/peers count for torrent and update torrent data in the db. The torrent protocols are implemented in [demagnetize](https://github.com/jwodder/demagnetize) library. But it doesn't support our requirement. We need to implement the functionality by modifying on top of it.

**Comment by ragmehos** [comment]
With https://github.com/mhdzumair/MediaFusion/pull/90 - its possible to get the peers count from bitsearch or from prowlarr - so should be easier to handle it than having to modify demagnetize library.

**Comment by mhdzumair** [comment]
A UDP implementation exists for obtaining the data we need: https://github.com/project-mk-ultra/torrent-tracker-scraper.

However, the current solution has limitations. While it functions somewhat, the seed count is reported per tracker, not aggregated. We require the total seed count without duplicate entries across trackers. Additionally, supporting HTTP trackers is essential.
