### ISSUE TITLE
Please add Premiumize as a debrid service

### ISSUE THREAD

**Issue by icpryde** [mhdzumair/MediaFusion#87]
Would it be possible to add support for Premiumize? It's a very popular Debrid service and noticed it wasn't available among the other Debrid services. 

https://www.premiumize.me/

**Comment by mhdzumair** [comment]
You're welcome to contribute.

**Comment by icpryde** [comment]
I know torrentio has the premiumize service i quickly looked at the code but i have no idea how to make that work with your addon as i'm not a programmer

https://github.com/TheBeastLT/torrentio-scraper/blob/master/addon/moch/premiumize.js

**Comment by mhdzumair** [comment]
Please join our telegram group. If you could able provide temporary the access to test the feature, then we could add support for it.

**Comment by mhdzumair** [comment]
Added the integration https://github.com/mhdzumair/MediaFusion/commit/f498daf6feea25e5fa2a37aba767263967cb01a9
