### ISSUE TITLE
Improve the documentations

### ISSUE THREAD

**Issue by mhdzumair** [mhdzumair/MediaFusion#9]
As part of the `hacktoberfest`, I would like to get contributions to improving the documentations if you feel anything need to be updated.

**Comment by Ahzem** [comment]
Assign me

**Comment by mhdzumair** [comment]
> Assign me

@Ahzem this is a general issue. Once you create a PR for any improvements, ill create an issue according to the changes you made. Feel free to contribute. 

Happy Contributions 🥇 👍

**Comment by mhdzumair** [comment]
@SuryaCreatX please create a PR. I can create an issue according to your changes.

**Comment by mhdzumair** [comment]
@SuryaCreatX may be you can improve the documentation about the streaming providers seedr and real-debrid 

Happy Collaboration :+1:
