### ISSUE TITLE
mediafusion.fun down - url cannot be resolved

### ISSUE THREAD

**Issue by binuengoor** [mhdzumair/MediaFusion#96]
service/url is down currently - EST 09PM - Feb 3 2024

It has been down for the past few hours.

**Comment by mhdzumair** [comment]
DNS has been updated. Now you can access.

**Comment by binuengoor** [comment]
@mhdzumair https://mediafusion.fun is still down for me. Does it take some time to resolve?

**Comment by mhdzumair** [comment]
could you check from incognito mode? It sometimes takes for DNS caching.

**Comment by binuengoor** [comment]
I think it took a few minutes. now its working. thanks for your awesome work.
