### ISSUE TITLE
Public IP while using real debrid?

### ISSUE THREAD

**Issue by lolwalla** [mhdzumair/MediaFusion#97]
When I am streaming a show/movie with Media fusion, the public IP used in Real Debrid is not my device's public IP. The public IP seems to be a server in Singapore. Why is this so?

This could potentially ban me form Real Debrid, since Real Debrid allows only the use of one public IP at a time. If I am streaming a show with Media Fusion in one device and a different show with a different add on on a different device I will be accessing Real Debrid with 2 different IPs (even though the location of both the devices are same and I am not using VPN). Any plans to change this behavior? 

Also refer to [this post in r/streamioaddons](https://www.reddit.com/r/StremioAddons/comments/17p6ddh/mediafusion_uses_different_ip_address/).

**Comment by mhdzumair** [comment]
As I explained in the Subreddit post, The MediaFusion server running on Singapore region, therefore the RealDebrid function https://github.com/mhdzumair/MediaFusion/blob/develop/streaming_providers/realdebrid/utils.py#L20-L62 runs in the server. Not in your local. 

I suggest you to run the MediaFusion from your local, I'm planning to create a documentation about setting up everything within few mins.

**Comment by mhdzumair** [comment]
Hi @lolwalla please see the detail guideline on setting up everything in your local https://github.com/mhdzumair/MediaFusion/blob/develop/deployment/README.md  🤖
