### ISSUE TITLE
https://mediafusion.fun host is down

### ISSUE THREAD

**Issue by binuengoor** [mhdzumair/MediaFusion#98]
yesterday the dns issue was preventing the url from being accessible. now the host seems to be down.

<img width="1222" alt="Screenshot 2024-02-04 at 3 14 21 PM" src="https://github.com/mhdzumair/MediaFusion/assets/62013964/fc9d9e07-322a-4fda-9559-ae2de72e0ba1">

**Comment by mhdzumair** [comment]
The server is unable to keep up on high load on peak time. The better alternative is to setup mediafusion in your local. The guide will be available on next release.

**Comment by mhdzumair** [comment]
make few improvements further. 
- added hpa with cpu utilization based metric
- use gunicorn with multi worker. 
i can see its much better on peak time as of yesterday. so closing this as done
