### ISSUE TITLE
Torrentio stream list not interlocked

### ISSUE THREAD

**Issue by hsp1020** [mhdzumair/MediaFusion#99]
![Screenshot_20240207_224356_Stremio](https://github.com/mhdzumair/MediaFusion/assets/125277818/b2327b30-3962-4a4c-b8b1-aaf7ef727eaa)
Torrentio addon stream list

![Screenshot_20240207_224448_Stremio](https://github.com/mhdzumair/MediaFusion/assets/125277818/2001f201-ab60-46d8-9faa-e70b73e4d4b1)
MediaFusion addon stream list

I understand that MediaFusion is linked to the stream list of Torrentio.
However, after installing Torrentio addon as shown in the picture, the stream list and the MediaFusion stream list are different.
Because of this, I'm having a hard time using it.

**Comment by mhdzumair** [comment]
Hi @hsp1020. As a discussion with Torrentio dev, I've decided to disable scraping streams from Torrentio on the official user-facing website https://mediafusion.fun.  The previously scraped data will remain as-is, but will be gradually replaced by Prowlarr indexers.

The good news is that we've integrated Prowlarr indexers, except for TamilBlasters and TamilMV. The Prowlarr indexer data will be available.

Alternatively, you can set up the MediaFusion addon completely locally with Torrentio stream scraping enabled. (It's up to you for not overloading the Torrentio 😅😅😅)

**Comment by hsp1020** [comment]
If it's right to set Torrentio stream scraping enabled like a screenshot, I've already set it up that way and I'm using the media fusion add-on. Still, the stream list doesn't pop up.

**Comment by hsp1020** [comment]
If it's right to set Torrentio stream scraping enabled like a screenshot, I've already set it up that way and I'm using the media fusion add-on. Still, the stream list doesn't pop up.

**Comment by mhdzumair** [comment]
> I've already set it up that way and I'm using the media fusion add-on. Still, the stream list doesn't pop up.

Have you setup the mediafusion addon on local?  not using the https://mediafusion.fun/

**Comment by hsp1020** [comment]
Just accessed https://mediafusion.fun/ and Torrentio Stream enabled and reinstalled. But things are the same. What am I supposed to do?

**Comment by mhdzumair** [comment]
> "As a discussion with Torrentio dev, I've decided to disable scraping streams from Torrentio on the official user-facing website https://mediafusion.fun/. The previously scraped data will remain as-is, but will be gradually replaced by Prowlarr indexers." 

as i mention earlier, the https://mediafusion.fun/ site won't give any new torrentio links. That feature is disabled by default. You have to set up this Add-on completely in your local to configure as your wish. 

To set up the add-on locally, please wait until i release the detail documentation.

**Comment by hsp1020** [comment]
When are you going to release the detail documentation?

**Comment by mhdzumair** [comment]
here is the detailed guideline https://github.com/mhdzumair/MediaFusion/blob/develop/deployment/README.md 🤖

**Comment by mhdzumair** [comment]
> I just saw the detail guidelines you posted. but I'm an Android version user. Is there no way to enabled Torrentio link on Android at all?

You can set up the add-on on any VPS server. After talking, I decided not to use the Torrentio scrap feature on https://mediafusion.fun because it makes torrentio extra load. The prowlarr scrapper adding more torrent by every seconds.
